export const MOCK_CATEGORIES = [
  { id: '1', name: '全部資源', slug: 'all' },
  { id: '2', name: '網頁開發', slug: 'web-dev' },
  { id: '3', name: '英語學習', slug: 'english' },
  { id: '4', name: '生物與生命科學', slug: 'biology' },
  { id: '5', name: '物理與化學實驗', slug: 'physics-chem' },
  { id: '6', name: '數位設計', slug: 'design' },
  { id: '7', name: '職場生產力', slug: 'productivity' },
  { id: '8', name: '財務理財', slug: 'finance' },
];

export const MOCK_RESOURCES = [
  // --- Web Development (20 items) ---
  { id: 'w1', title: 'GrandmaCan - 阿嬤的程式教室', description: '最受歡迎的繁體中文程式入門頻道。', url: 'https://www.youtube.com/@GrandmaCan', level: 'Beginner', media_type: 'YouTube', category_slug: 'web-dev', likes_count: 8500, language: '繁體中文' },
  { id: 'w2', title: '六角學院 (Hexschool)', description: '台灣前端開發首選學習平台。', url: 'https://www.hexschool.com/', level: 'Beginner', media_type: 'Course', category_slug: 'web-dev', likes_count: 12000, language: '繁體中文' },
  { id: 'w3', title: '彭彭的教學時光', description: '邏輯極其清晰的 Python 與 JS 教學。', url: 'https://training.dotpot.net/', level: 'Beginner', media_type: 'Video', category_slug: 'web-dev', likes_count: 6700, language: '繁體中文' },
  { id: 'w4', title: 'iT 幫幫忙 鐵人賽', description: '台灣最大的技術分享社群。', url: 'https://ithelp.ithome.com.tw/ironman', level: 'Intermediate', media_type: 'Article', category_slug: 'web-dev', likes_count: 15000, language: '繁體中文' },
  { id: 'w5', title: 'freeCodeCamp (繁體版)', description: '全球最強的免費課程與認證。', url: 'https://www.freecodecamp.org/chinese/', level: 'Beginner', media_type: 'Course', category_slug: 'web-dev', likes_count: 22000, language: '繁體中文' },
  { id: 'w6', title: 'The Odin Project', description: '開源專案導向課程，建立完整作品集。', url: 'https://www.theodinproject.com/', level: 'Intermediate', media_type: 'Course', category_slug: 'web-dev', likes_count: 9800, language: '英文/中字' },
  { id: 'w7', title: 'Fireship', description: '快節奏介紹新技術，適合追蹤趨勢。', url: 'https://www.youtube.com/@Fireship', level: 'Advanced', media_type: 'YouTube', category_slug: 'web-dev', likes_count: 18000, language: '英文/中字' },
  { id: 'w8', title: 'MDN Web Docs', description: 'Web 開發者的技術文檔聖經。', url: 'https://developer.mozilla.org/zh-TW/', level: 'Beginner', media_type: 'Article', category_slug: 'web-dev', likes_count: 25000, language: '繁體中文' },
  { id: 'w9', title: 'Traversy Media', description: '最紮實的 Web 開發 Crash Course。', url: 'https://www.youtube.com/@TraversyMedia', level: 'Intermediate', media_type: 'YouTube', category_slug: 'web-dev', likes_count: 11000, language: '英文/中字' },
  { id: 'w10', title: 'Net Ninja', description: '極高品質的前端框架教學。', url: 'https://www.youtube.com/@NetNinja', level: 'Intermediate', media_type: 'YouTube', category_slug: 'web-dev', likes_count: 9200, language: '英文/中字' },
  { id: 'w11', title: 'CSS-Tricks', description: '掌握 CSS 與網頁版排的最佳資源。', url: 'https://css-tricks.com/', level: 'Intermediate', media_type: 'Article', category_slug: 'web-dev', likes_count: 8500, language: '英文' },
  { id: 'w12', title: 'Frontend Mentor', description: '透過實作真實的 UI 挑戰來增進前端技能。', url: 'https://www.frontendmentor.io/', level: 'Intermediate', media_type: 'Tool', category_slug: 'web-dev', likes_count: 7200, language: '英文' },
  { id: 'w13', title: 'W3Schools 中文', description: '最易上手的基礎代碼練習站。', url: 'https://www.w3school.com.cn/', level: 'Beginner', media_type: 'Article', category_slug: 'web-dev', likes_count: 15000, language: '簡體中文' },
  { id: 'w14', title: 'Dev.to', description: '全球開發者分享心得與技術的文章平台。', url: 'https://dev.to/', level: 'All Levels', media_type: 'Article', category_slug: 'web-dev', likes_count: 10000, language: '英文' },
  { id: 'w15', title: 'Scrimba', description: '互動式影片教學，能邊看邊寫代碼。', url: 'https://scrimba.com/', level: 'Beginner', media_type: 'Course', category_slug: 'web-dev', likes_count: 6400, language: '英文' },
  { id: 'w16', title: 'Web.dev', description: 'Google 推出的 Web 效能與最佳實踐指南。', url: 'https://web.dev/', level: 'Advanced', media_type: 'Article', category_slug: 'web-dev', likes_count: 9100, language: '英文' },
  { id: 'w17', title: 'Hyperplexed', description: '極致前端動畫與創意 UI 實作。', url: 'https://www.youtube.com/@Hyperplexed', level: 'Advanced', media_type: 'YouTube', category_slug: 'web-dev', likes_count: 5500, language: '英文/中字' },
  { id: 'w18', title: 'JavaScript.info', description: '從基礎到進階的 JS 教學，非常完整。', url: 'https://zh.javascript.info/', level: 'All Levels', media_type: 'Article', category_slug: 'web-dev', likes_count: 12000, language: '繁體中文' },
  { id: 'w19', title: 'Kevin Powell', description: '專教 CSS 寫法與響應式設計的專家。', url: 'https://www.youtube.com/@KevinPowell', level: 'Intermediate', media_type: 'YouTube', category_slug: 'web-dev', likes_count: 7800, language: '英文/中字' },
  { id: 'w20', title: 'Web Dev Simplified', description: '簡化複雜概念，讓你聽懂背後原理。', url: 'https://www.youtube.com/@WebDevSimplified', level: 'Intermediate', media_type: 'YouTube', category_slug: 'web-dev', likes_count: 9500, language: '英文/中字' },

  // --- English (20 items) ---
  { id: 'e1', title: '阿滴英文', description: '台灣最大英語學習 YouTube 頻道。', url: 'https://www.youtube.com/@RayDuEnglish', level: 'Beginner', media_type: 'YouTube', category_slug: 'english', likes_count: 18000, language: '繁體中文' },
  { id: 'e2', title: 'VoiceTube', description: '看影片學英文，即時字典與聽力練習。', url: 'https://tw.voicetube.com/', level: 'All Levels', media_type: 'Tool', category_slug: 'english', likes_count: 14000, language: '繁體中文' },
  { id: 'e3', title: '賓狗單字', description: '結合時事新聞學單字，幽默有趣。', url: 'https://www.facebook.com/bingobilingual/', level: 'Beginner', media_type: 'Video', category_slug: 'english', likes_count: 5500, language: '繁體中文' },
  { id: 'e4', title: '希平方', description: '系統化複習與聽寫訓練平台。', url: 'https://www.hopenglish.com/', level: 'Intermediate', media_type: 'Course', category_slug: 'english', likes_count: 8200, language: '繁體中文' },
  { id: 'e5', title: 'BBC Learning English', description: '經典高品質資源，含 6 Minute English。', url: 'https://www.bbc.co.uk/learningenglish', level: 'Intermediate', media_type: 'Video', category_slug: 'english', likes_count: 11000, language: '英文/中字' },
  { id: 'e6', title: 'VOA Learning English', description: '使用簡單辭彙與緩慢語速。', url: 'https://learningenglish.voanews.com/', level: 'Beginner', media_type: 'Video', category_slug: 'english', likes_count: 9500, language: '英文/中字' },
  { id: 'e7', title: 'Duolingo', description: '遊戲化語言學習，輕鬆上手。', url: 'https://www.duolingo.com/', level: 'Beginner', media_type: 'Tool', category_slug: 'english', likes_count: 35000, language: '繁體中文' },
  { id: 'e8', title: 'TED-Ed', description: '啟發性的教育短片，支援多國字幕。', url: 'https://ed.ted.com/', level: 'Intermediate', media_type: 'Video', category_slug: 'english', likes_count: 22000, language: '中文字幕' },
  { id: 'e9', title: 'WORD UP', description: '台灣最強單字 App，結合 AI 複習。', url: 'https://www.wordup.com.tw/', level: 'All Levels', media_type: 'Tool', category_slug: 'english', likes_count: 7300, language: '繁體中文' },
  { id: 'e10', title: 'English with Lucy', description: '學習道地的正統英國腔與高級辭彙。', url: 'https://www.youtube.com/@EnglishwithLucy', level: 'Advanced', media_type: 'YouTube', category_slug: 'english', likes_count: 12000, language: '英文/中字' },
  { id: 'e11', title: 'Grammarly Blog', description: '提升寫作技巧與糾正語法錯誤。', url: 'https://www.grammarly.com/blog/', level: 'Intermediate', media_type: 'Article', category_slug: 'english', likes_count: 8800, language: '英文' },
  { id: 'e12', title: 'CNN 10', description: '10 分鐘新聞，適合中進階聽力練習。', url: 'https://edition.cnn.com/cnn10', level: 'Advanced', media_type: 'Video', category_slug: 'english', likes_count: 6500, language: '英文' },
  { id: 'e13', title: 'Breaking News English', description: '依難度分級的新聞閱讀與練習。', url: 'https://breakingnewsenglish.com/', level: 'All Levels', media_type: 'Article', category_slug: 'english', likes_count: 4200, language: '英文' },
  { id: 'e14', title: 'Cambridge Dictionary', description: '全球最權威的英英/英漢在線字典。', url: 'https://dictionary.cambridge.org/zht/', level: 'All Levels', media_type: 'Tool', category_slug: 'english', likes_count: 20000, language: '繁體中文' },
  { id: 'e15', title: 'Merriam-Webster', description: '美國老牌字典，單字解析極其深刻。', url: 'https://www.merriam-webster.com/', level: 'Advanced', media_type: 'Tool', category_slug: 'english', likes_count: 11000, language: '英文' },
  { id: 'e16', title: 'English Class 101', description: '分場景情境式教學，資源極其龐大。', url: 'https://www.englishclass101.com/', level: 'All Levels', media_type: 'Course', category_slug: 'english', likes_count: 5100, language: '英文' },
  { id: 'e17', title: 'Rachel\'s English', description: '發音專家，改善美式發音細節。', url: 'https://www.youtube.com/@rachelsenglish', level: 'Intermediate', media_type: 'YouTube', category_slug: 'english', likes_count: 9200, language: '英文/中字' },
  { id: 'e18', title: 'LingQ', description: '透過閱讀你有興趣的內容來學語言。', url: 'https://www.lingq.com/', level: 'Intermediate', media_type: 'Tool', category_slug: 'english', likes_count: 3800, language: '繁體中文' },
  { id: 'e19', title: 'British Council', description: '官方法定資源，適合準備雅思檢定。', url: 'https://learnenglish.britishcouncil.org/', level: 'Advanced', media_type: 'Course', category_slug: 'english', likes_count: 14000, language: '英文' },
  { id: 'e20', title: 'DeepL Write', description: 'AI 修改英文作文的自然與流暢度。', url: 'https://www.deepl.com/write', level: 'Advanced', media_type: 'Tool', category_slug: 'english', likes_count: 15000, language: '繁體中文' },

  // --- Biology (15 items) ---
  { id: 'b1', title: 'PanSci 泛科學', description: '台灣最大科普站，解析生物與醫學。', url: 'https://pansci.asia/', level: 'All Levels', media_type: 'Article', category_slug: 'biology', likes_count: 11000, language: '繁體中文' },
  { id: 'b2', title: '均一生物', description: '台灣國高中生必備的生物教學資源。', url: 'https://www.junyiacademy.org/science/biology', level: 'Beginner', media_type: 'Course', category_slug: 'biology', likes_count: 9500, language: '繁體中文' },
  { id: 'b3', title: 'LabXchange', description: '哈佛開發，虛擬生物實驗室操作。', url: 'https://www.labxchange.org/', level: 'Advanced', media_type: 'Tool', category_slug: 'biology', likes_count: 6800, language: '中字', is_experiment: true },
  { id: 'b4', title: 'Amoeba Sisters', description: '可愛動畫講解複雜的細胞遺傳學。', url: 'https://www.youtube.com/@AmoebaSisters', level: 'Beginner', media_type: 'YouTube', category_slug: 'biology', likes_count: 7200, language: '英文/中字' },
  { id: 'b5', title: 'Kurzgesagt', description: '絕美動態設計，探討微觀與宏觀科學。', url: 'https://www.youtube.com/@kurzgesagt', level: 'All Levels', media_type: 'YouTube', category_slug: 'biology', likes_count: 45000, language: '中文字幕' },
  { id: 'b6', title: 'Nature', description: '全球最權威的科學期刊，掌握研究尖端。', url: 'https://www.nature.com/', level: 'Advanced', media_type: 'Article', category_slug: 'biology', likes_count: 18000, language: '英文' },
  { id: 'b7', title: 'ScienceDaily', description: '每日更新全球最新的健康與生物新聞。', url: 'https://www.sciencedaily.com/', level: 'Intermediate', media_type: 'Article', category_slug: 'biology', likes_count: 5400, language: '英文' },
  { id: 'b8', title: 'BioDigital', description: '3D 人體解剖與病理互動式平台。', url: 'https://www.biodigital.com/', level: 'Advanced', media_type: 'Tool', category_slug: 'biology', likes_count: 3200, language: '英文' },
  { id: 'b9', title: 'Osmosis', description: '醫學生與生理學學習的最佳動畫庫。', url: 'https://www.youtube.com/@osmosis', level: 'Advanced', media_type: 'YouTube', category_slug: 'biology', likes_count: 12000, language: '英文/中字' },
  { id: 'b10', title: 'HHMI BioInteractive', level: 'Advanced', description: '提供極高品質的演化、生態與生理學互動教材，專家級首選。', url: 'https://www.biointeractive.org/', media_type: 'Tool', category_slug: 'biology', likes_count: 4100, language: '英文/中字' },
  { id: 'b11', title: 'Cells Alive', description: '探索微觀細胞世界與微生物動態。', url: 'https://www.cellsalive.com/', level: 'Beginner', media_type: 'Article', category_slug: 'biology', likes_count: 2800, language: '英文' },
  { id: 'b12', title: 'Biology Online', description: '生物學辭典與全面知識庫。', url: 'https://www.biologyonline.com/', level: 'All Levels', media_type: 'Article', category_slug: 'biology', likes_count: 3500, language: '英文' },
  { id: 'b13', title: 'Visible Body', description: '直觀學習人體結構的 3D 工具。', url: 'https://www.visiblebody.com/learn/', level: 'Advanced', media_type: 'Tool', category_slug: 'biology', likes_count: 1900, language: '英文' },
  { id: 'b14', title: 'Ninja Nerd', description: '最強大的免費醫學與生理學講座。', url: 'https://www.youtube.com/@NinjaNerdOfficial', level: 'Advanced', media_type: 'YouTube', category_slug: 'biology', likes_count: 6100, language: '英文' },
  { id: 'b15', title: '生物小站', description: '台灣整理的國高中生物筆記精華。', url: 'http://biostation.org/', level: 'Beginner', media_type: 'Article', category_slug: 'biology', likes_count: 2100, language: '繁體中文' },

  // --- Physics & Chemistry (15 items) ---
  { id: 's1', title: 'PhET 互動教材', description: '物理、化學概念視覺化的最強工具。', url: 'https://phet.colorado.edu/zh_TW/', level: 'Beginner', media_type: 'Tool', category_slug: 'physics-chem', likes_count: 18500, language: '繁體中文', is_experiment: true },
  { id: 's2', title: 'Veritasium', description: '全球頂尖物理教育，破解直覺陷阱。', url: 'https://www.youtube.com/@veritasium', level: 'Intermediate', media_type: 'YouTube', category_slug: 'physics-chem', likes_count: 32000, language: '中文字幕' },
  { id: 's3', title: 'LIS 科學教材', description: '台灣開發，用故事啟發科學思考。', url: 'https://lis.org.tw/', level: 'Beginner', media_type: 'Video', category_slug: 'physics-chem', likes_count: 6500, language: '繁體中文' },
  { id: 's4', title: 'Periodic Videos', description: '諾丁漢大學帶你認識週期表元素。', url: 'https://www.periodicvideos.com/', level: 'Intermediate', media_type: 'Video', category_slug: 'physics-chem', likes_count: 4200, language: '提供中字' },
  { id: 's5', title: 'SmarterEveryDay', description: '從科學家視角觀察生活中的力學。', url: 'https://www.youtube.com/@smartereveryday', level: 'Intermediate', media_type: 'YouTube', category_slug: 'physics-chem', likes_count: 14000, language: '中文字幕' },
  { id: 's6', title: 'Mark Rober', description: '前 NASA 工程師，實作超有趣物理裝置。', url: 'https://www.youtube.com/@markrober', level: 'Beginner', media_type: 'YouTube', category_slug: 'physics-chem', likes_count: 55000, language: '中文字幕' },
  { id: 's7', title: 'Brilliant', description: '透過互動式解題來學習數學與物理。', url: 'https://brilliant.org/', level: 'All Levels', media_type: 'Course', category_slug: 'physics-chem', likes_count: 21000, language: '英文' },
  { id: 's8', title: 'Physics Classroom', description: '結構完整、圖表清晰的物理複習站。', url: 'https://www.physicsclassroom.com/', level: 'Intermediate', media_type: 'Article', category_slug: 'physics-chem', likes_count: 3800, language: '英文' },
  { id: 's9', title: 'MinutePhysics', description: '用一分鐘的手繪動畫解釋物理定律。', url: 'https://www.youtube.com/@minutephysics', level: 'Beginner', media_type: 'YouTube', category_slug: 'physics-chem', likes_count: 12000, language: '中文字幕' },
  { id: 's10', title: 'Periodic Table', description: '動態、可點擊的元素週期表與性質。', url: 'https://ptable.com/', level: 'Beginner', media_type: 'Tool', category_slug: 'physics-chem', likes_count: 8900, language: '繁體中文' },
  { id: 's11', title: 'ChemLibreTexts', description: '全球最大、最完整的化學教科書。', url: 'https://chem.libretexts.org/', level: 'Advanced', media_type: 'Article', category_slug: 'physics-chem', likes_count: 4500, language: '英文' },
  { id: 's12', title: 'WolframAlpha', description: '科學計算搜尋引擎，處理複雜物理。', url: 'https://www.wolframalpha.com/', level: 'Advanced', media_type: 'Tool', category_slug: 'physics-chem', likes_count: 13000, language: '英文' },
  { id: 's13', title: 'Physics Girl', description: '透過生活實驗展示有趣的物理現象。', url: 'https://www.youtube.com/@physicsgirl', level: 'Beginner', media_type: 'YouTube', category_slug: 'physics-chem', likes_count: 9400, language: '英文/中字' },
  { id: 's14', title: 'ACS Reactions', description: '用化學原理解釋日常生活的一切。', url: 'https://www.youtube.com/@ACSReactions', level: 'Intermediate', media_type: 'YouTube', category_slug: 'physics-chem', likes_count: 7200, language: '英文/中字' },
  { id: 's15', title: '數感實驗室', description: '將數學與數據視覺化，生活邏輯首選。', url: 'https://numeracyly.com/', level: 'All Levels', media_type: 'Article', category_slug: 'physics-chem', likes_count: 7200, language: '繁體中文' },

  // --- Design (15 items) ---
  { id: 'd1', title: 'Papaya 電腦教室', description: '速成 PS, AI, Premiere 與 Figma。', url: 'https://www.youtube.com/@PapayaClass', level: 'Beginner', media_type: 'YouTube', category_slug: 'design', likes_count: 15000, language: '繁體中文' },
  { id: 'd2', title: '設計大舌頭', description: '深談 UI/UX 理論與產品實務。', url: 'https://designtips.today/', level: 'Intermediate', media_type: 'Article', category_slug: 'design', likes_count: 9400, language: '繁體中文' },
  { id: 'd3', title: '郭查理', description: '拆解經典設計背後的邏輯與審美。', url: 'https://www.youtube.com/@CharlieKuo', level: 'Intermediate', media_type: 'YouTube', category_slug: 'design', likes_count: 5200, language: '繁體中文' },
  { id: 'd4', title: 'Dribbble', description: '全球頂尖設計師的作品展示與社群。', url: 'https://dribbble.com/', level: 'All Levels', media_type: 'Tool', category_slug: 'design', likes_count: 32000, language: '國際化' },
  { id: 'd5', title: 'Adobe Color', description: '掌握色彩理論與自動配色方案。', url: 'https://color.adobe.com/zh/create/color-wheel', level: 'Beginner', media_type: 'Tool', category_slug: 'design', likes_count: 22000, language: '繁體中文' },
  { id: 'd6', title: 'Canva Design School', description: '零基礎也能學會的設計基礎課。', url: 'https://www.canva.com/designschool/', level: 'Beginner', media_type: 'Course', category_slug: 'design', likes_count: 12000, language: '繁體中文' },
  { id: 'd7', title: 'Behance', description: '探索各個領域最具創意的作品集。', url: 'https://www.behance.net/', level: 'All Levels', media_type: 'Tool', category_slug: 'design', likes_count: 45000, language: '國際化' },
  { id: 'd8', title: 'Awwwards', description: '評選全球年度最佳網頁設計。', url: 'https://www.awwwards.com/', level: 'Advanced', media_type: 'Article', category_slug: 'design', likes_count: 9500, language: '英文' },
  { id: 'd9', title: 'Satori Graphics', description: '版排、字體與 LOGO 設計的高端教學。', url: 'https://www.youtube.com/@SatoriGraphics', level: 'Intermediate', media_type: 'YouTube', category_slug: 'design', likes_count: 8100, language: '英文/中字' },
  { id: 'd10', title: 'Flux Academy', description: '從設計轉型為自由接案者的全攻略。', url: 'https://www.youtube.com/@FluxAcademy', level: 'Advanced', media_type: 'YouTube', category_slug: 'design', likes_count: 6800, language: '英文/中字' },
  { id: 'd11', title: 'IDF', description: 'UI/UX 研究、使用者心理的學術庫。', url: 'https://www.interaction-design.org/', level: 'Advanced', media_type: 'Article', category_slug: 'design', likes_count: 5100, language: '英文' },
  { id: 'd12', title: 'Material Design', description: 'Google 推出的系統化設計語言規範。', url: 'https://m3.material.io/', level: 'Advanced', media_type: 'Tool', category_slug: 'design', likes_count: 14000, language: '英文' },
  { id: 'd13', title: 'Adobe Font', description: '全球字體靈感與版排美學。', url: 'https://fonts.adobe.com/', level: 'All Levels', media_type: 'Tool', category_slug: 'design', likes_count: 7300, language: '繁體中文' },
  { id: 'd14', title: 'Fontshare', description: '高品質免費商用字體資源站。', url: 'https://www.fontshare.com/', level: 'Beginner', media_type: 'Tool', category_slug: 'design', likes_count: 3200, language: '英文' },
  { id: 'd15', title: 'Smashing Magazine', description: '專業設計師與開發者的深度雜誌。', url: 'https://www.smashingmagazine.com/categories/design/', level: 'Advanced', media_type: 'Article', category_slug: 'design', likes_count: 11000, language: '英文' },

  // --- Productivity (15 items) ---
  { id: 'p1', title: '電腦玩物', description: 'Notion 與 AI 工作流大師。', url: 'https://www.playpcesor.com/', level: 'All Levels', media_type: 'Article', category_slug: 'productivity', likes_count: 18000, language: '繁體中文' },
  { id: 'p2', title: '朱騏', description: 'Obsidian 與卡片盒筆記法推廣者。', url: 'https://medium.com/@mickey-chi', level: 'Intermediate', media_type: 'Article', category_slug: 'productivity', likes_count: 5600, language: '繁體中文' },
  { id: 'p3', title: '雷蒙三十', description: 'Notion 系統與數位遊牧實踐分享。', url: 'https://raymondhouch.com/', level: 'Intermediate', media_type: 'Article', category_slug: 'productivity', likes_count: 7200, language: '繁體中文' },
  { id: 'p4', title: 'Ali Abdaal', description: '教你如何高效、快樂且不焦慮。', url: 'https://www.youtube.com/@aliabdaal', level: 'All Levels', media_type: 'YouTube', category_slug: 'productivity', likes_count: 32000, language: '中文字幕' },
  { id: 'p5', title: 'Thomas Frank', description: 'Notion 專家，教你構建第二大腦。', url: 'https://www.youtube.com/@ThomasFrank', level: 'All Levels', media_type: 'YouTube', category_slug: 'productivity', likes_count: 25000, language: '中文字幕' },
  { id: 'p6', title: 'Lifehacker', description: '優化生活與工作效率的技巧站。', url: 'https://lifehacker.com/', level: 'Beginner', media_type: 'Article', category_slug: 'productivity', likes_count: 15000, language: '英文' },
  { id: 'p7', title: 'Zapier Blog', description: '掌握自動化工具，釋放你的時間。', url: 'https://zapier.com/blog/', level: 'Advanced', media_type: 'Article', category_slug: 'productivity', likes_count: 4200, language: '英文' },
  { id: 'p8', title: 'Todoist Blog', description: '專注於任務管理與目標達成的深度文。', url: 'https://todoist.com/blog', level: 'Intermediate', media_type: 'Article', category_slug: 'productivity', likes_count: 6800, language: '英文' },
  { id: 'p9', title: 'RescueTime', description: '分析你的電腦使用時間並提升專注。', url: 'https://www.rescuetime.com/blog/', level: 'All Levels', media_type: 'Tool', category_slug: 'productivity', likes_count: 3100, language: '英文' },
  { id: 'p10', title: 'Trello Blog', description: '團隊協作與看板管理的最佳實務。', url: 'https://blog.trello.com/', level: 'Intermediate', media_type: 'Article', category_slug: 'productivity', likes_count: 5400, language: '英文' },
  { id: 'p11', title: 'Notion Templates', description: '探索全球最強大的 Notion 模板。', url: 'https://www.notion.so/templates', level: 'All Levels', media_type: 'Tool', category_slug: 'productivity', likes_count: 42000, language: '國際化' },
  { id: 'p12', title: 'Evernote Blog', description: '老牌筆記工具的生產力方法論。', url: 'https://evernote.com/blog/', level: 'Intermediate', media_type: 'Article', category_slug: 'productivity', likes_count: 8100, language: '英文' },
  { id: 'p13', title: 'Product Hunt', description: '每天發現全球最新、最酷的數位工具。', url: 'https://www.producthunt.com/', level: 'All Levels', media_type: 'Tool', category_slug: 'productivity', likes_count: 55000, language: '英文' },
  { id: 'p14', title: 'Freedom', description: '屏蔽干擾網站，找回深度工作時間。', url: 'https://freedom.to/blog/', level: 'Beginner', media_type: 'Tool', category_slug: 'productivity', likes_count: 2400, language: '英文' },
  { id: 'p15', title: 'Papaya 辦公效率', description: '速成 Excel, Word, PPT 職場技能。', url: 'https://www.youtube.com/@PapayaClass', level: 'Beginner', media_type: 'YouTube', category_slug: 'productivity', likes_count: 14000, language: '繁體中文' },

  // --- Finance (15 items) ---
  { id: 'f1', title: '財報狗', description: '台股基本面分析與財報研究首選。', url: 'https://statementdog.com/', level: 'Intermediate', media_type: 'Tool', category_slug: 'finance', likes_count: 12000, language: '繁體中文' },
  { id: 'f2', title: '綠角財經', description: '指數化投資與 ETF 的聖經級部落格。', url: 'https://greenhornfinancediary.blogspot.com/', level: 'Advanced', media_type: 'Article', category_slug: 'finance', likes_count: 9800, language: '繁體中文' },
  { id: 'f3', title: '柴鼠兄弟', description: '理財概念生活化，推薦 ETF 懶人包。', url: 'https://www.youtube.com/@ZRBros', level: 'Beginner', media_type: 'YouTube', category_slug: 'finance', likes_count: 15000, language: '繁體中文' },
  { id: 'f4', title: 'Investopedia', description: '金融界的百科全書，學術定義極準確。', url: 'https://www.investopedia.com/', level: 'All Levels', media_type: 'Article', category_slug: 'finance', likes_count: 35000, language: '英文' },
  { id: 'f5', title: 'Morningstar', description: '晨星評級，深度的基金與股票研究。', url: 'https://www.morningstar.com/', level: 'Advanced', media_type: 'Tool', category_slug: 'finance', likes_count: 12000, language: '英文' },
  { id: 'f6', title: 'Yahoo Finance', description: '即時市場行情與各國股市追蹤。', url: 'https://finance.yahoo.com/', level: 'All Levels', media_type: 'Tool', category_slug: 'finance', likes_count: 55000, language: '英文/中文' },
  { id: 'f7', title: 'CNBC Finance', description: '全球商業新聞與突發財經資訊。', url: 'https://www.cnbc.com/finance/', level: 'Intermediate', media_type: 'Article', category_slug: 'finance', likes_count: 18000, language: '英文' },
  { id: 'f8', title: '股癌 (Gooaye)', description: '掌握市場最前線的情緒與洞察。', url: 'https://www.facebook.com/Gooaye', level: 'All Levels', media_type: 'Video', category_slug: 'finance', likes_count: 32000, language: '繁體中文' },
  { id: 'f9', title: 'Graham Stephan', description: '教你省錢、投資房產與增加被動收入。', url: 'https://www.youtube.com/@GrahamStephan', level: 'Beginner', media_type: 'YouTube', category_slug: 'finance', likes_count: 24000, language: '中文字幕' },
  { id: 'f10', title: 'MarketWatch', description: '市場即時分析與經濟數據解讀。', url: 'https://www.marketwatch.com/', level: 'Advanced', media_type: 'Article', category_slug: 'finance', likes_count: 9500, language: '英文' },
  { id: 'f11', title: 'The Motley Fool', description: '深度的個股分析與長期投資建議。', url: 'https://www.fool.com/', level: 'Intermediate', media_type: 'Article', category_slug: 'finance', likes_count: 8200, language: '英文' },
  { id: 'f12', title: 'Seeking Alpha', description: '集結眾多分析師觀點的投資社群。', url: 'https://seekingalpha.com/', level: 'Advanced', media_type: 'Article', category_slug: 'finance', likes_count: 6100, language: '英文' },
  { id: 'f13', title: '幣優 (BitUniverse)', description: '量化交易與加密貨幣資產管理。', url: 'https://www.bituniverse.org/', level: 'Advanced', media_type: 'Tool', category_slug: 'finance', likes_count: 3500, language: '繁體中文' },
  { id: 'f14', title: 'Khan Academy Finance', description: '從頭學習貨幣、利息與資本市場。', url: 'https://www.khanacademy.org/economics-finance-domain/core-finance', level: 'Beginner', media_type: 'Course', category_slug: 'finance', likes_count: 12000, language: '提供中字' },
  { id: 'f15', title: 'ETF.com', description: '最專業的 ETF 資料庫與比較工具。', url: 'https://www.etf.com/', level: 'Advanced', media_type: 'Tool', category_slug: 'finance', likes_count: 4800, language: '英文' },
];
