import { VocabWord } from "../vocab-data";

export const ELEMENTARY_VOCAB: VocabWord[] = [
  { id: 'e1', word: 'Apple', translation: '蘋果', definition: 'A round fruit with red or green skin.', example: 'I eat an apple every day.', level: 'Elementary' },
  { id: 'e2', word: 'Banana', translation: '香蕉', definition: 'A long yellow fruit with sweet soft flesh.', example: 'Monkeys like eating bananas.', level: 'Elementary' },
  { id: 'e3', word: 'Cat', translation: '貓', definition: 'A small animal with fur and a tail.', example: 'The cat is sleeping on the mat.', level: 'Elementary' },
  { id: 'e4', word: 'Dog', translation: '狗', definition: 'A common animal often kept as a pet.', example: 'My dog likes to run in the park.', level: 'Elementary' },
  { id: 'e5', word: 'Egg', translation: '蛋', definition: 'An oval object laid by a bird.', example: 'I want a boiled egg for breakfast.', level: 'Elementary' },
  { id: 'e6', word: 'Fish', translation: '魚', definition: 'An animal that lives in water.', example: 'There are many fish in the river.', level: 'Elementary' },
  { id: 'e7', word: 'Girl', translation: '女孩', definition: 'A female child.', example: 'The girl is wearing a pink dress.', level: 'Elementary' },
  { id: 'e8', word: 'Home', translation: '家', definition: 'The place where you live.', example: 'I go home after school.', level: 'Elementary' },
  { id: 'e9', word: 'Ice', translation: '冰', definition: 'Frozen water.', example: 'I like my water with ice.', level: 'Elementary' },
  { id: 'e10', word: 'Jar', translation: '罐子', definition: 'A glass container with a lid.', example: 'The cookie jar is empty.', level: 'Elementary' },
  { id: 'e11', word: 'Kite', translation: '風箏', definition: 'A toy that flies in the wind.', example: 'Let\'s fly a kite on a windy day.', level: 'Elementary' },
  { id: 'e12', word: 'Lamp', translation: '燈', definition: 'A device that gives light.', example: 'Turn on the lamp to read.', level: 'Elementary' },
  { id: 'e13', word: 'Milk', translation: '牛奶', definition: 'A white liquid from cows.', example: 'Drink your milk before bed.', level: 'Elementary' },
  { id: 'e14', word: 'Nose', translation: '鼻子', definition: 'The part of the face used for smelling.', example: 'The dog has a cold nose.', level: 'Elementary' },
  { id: 'e15', word: 'Orange', translation: '橘子', definition: 'A round orange fruit.', example: 'I like fresh orange juice.', level: 'Elementary' },
  { id: 'e16', word: 'Pig', translation: '豬', definition: 'A fat animal that lives on a farm.', example: 'The pig is playing in the mud.', level: 'Elementary' },
  { id: 'e17', word: 'Queen', translation: '皇后', definition: 'A woman who rules a country.', example: 'The queen lives in a big palace.', level: 'Elementary' },
  { id: 'e18', word: 'Rain', translation: '雨', definition: 'Water falling from the clouds.', example: 'I forgot my umbrella in the rain.', level: 'Elementary' },
  { id: 'e19', word: 'Sun', translation: '太陽', definition: 'The star that gives us light.', example: 'The sun is very hot today.', level: 'Elementary' },
  { id: 'e20', word: 'Tree', translation: '樹', definition: 'A tall plant with a trunk.', example: 'The cat is climbing the tree.', level: 'Elementary' },
  { id: 'e21', word: 'Uncle', translation: '叔叔/舅舅', definition: 'The brother of your father or mother.', example: 'My uncle gave me a gift.', level: 'Elementary' },
  { id: 'e22', word: 'Van', translation: '小貨車', definition: 'A vehicle used for moving things.', example: 'They moved to a new house in a van.', level: 'Elementary' },
  { id: 'e23', word: 'Water', translation: '水', definition: 'A clear liquid we drink.', example: 'I need to drink more water.', level: 'Elementary' },
  { id: 'e24', word: 'Yoyo', translation: '溜溜球', definition: 'A toy on a string.', example: 'He can do tricks with his yoyo.', level: 'Elementary' },
  { id: 'e25', word: 'Zoo', translation: '動物園', definition: 'A place where animals are kept.', example: 'Let\'s see the lions at the zoo.', level: 'Elementary' },
  { id: 'e26', word: 'Bread', translation: '麵包', definition: 'A common food made from flour.', example: 'I like butter on my bread.', level: 'Elementary' },
  { id: 'e27', word: 'Candy', translation: '糖果', definition: 'Sweet food made with sugar.', example: 'Too much candy is bad for teeth.', level: 'Elementary' },
  { id: 'e28', word: 'Duck', translation: '鴨子', definition: 'A bird that swims.', example: 'The duck says quack.', level: 'Elementary' },
  { id: 'e29', word: 'Fire', translation: '火', definition: 'Heat and light from burning.', example: 'Don\'t play with fire.', level: 'Elementary' },
  { id: 'e30', word: 'Game', translation: '遊戲', definition: 'Something you play for fun.', example: 'Do you want to play a game?', level: 'Elementary' },
  { id: 'e31', word: 'Hand', translation: '手', definition: 'Part of the body at the end of the arm.', example: 'Raise your hand if you know.', level: 'Elementary' },
  { id: 'e32', word: 'Jump', translation: '跳', definition: 'To push off the ground.', example: 'Can you jump over the log?', level: 'Elementary' },
  { id: 'e33', word: 'Leg', translation: '腿', definition: 'Part of the body used for walking.', example: 'He has long legs.', level: 'Elementary' },
  { id: 'e34', word: 'Moon', translation: '月亮', definition: 'The round object in the night sky.', example: 'The moon is bright tonight.', level: 'Elementary' },
  { id: 'e35', word: 'Night', translation: '夜晚', definition: 'The time when it is dark.', example: 'Stars shine at night.', level: 'Elementary' },
  { id: 'e36', word: 'Owl', translation: '貓頭鷹', definition: 'A bird that hunts at night.', example: 'The owl has big eyes.', level: 'Elementary' },
  { id: 'e37', word: 'Park', translation: '公園', definition: 'A public garden.', example: 'We play in the park.', level: 'Elementary' },
  { id: 'e38', word: 'Rice', translation: '米飯', definition: 'A common white grain.', example: 'I like eating rice.', level: 'Elementary' },
  { id: 'e39', word: 'Star', translation: '星星', definition: 'A light in the night sky.', example: 'I can see a falling star.', level: 'Elementary' },
  { id: 'e40', word: 'Train', translation: '火車', definition: 'A vehicle on tracks.', example: 'The train is very fast.', level: 'Elementary' },
  { id: 'e41', word: 'Watch', translation: '手錶/觀看', definition: 'Something to tell time or to look at.', example: 'Watch your step.', level: 'Elementary' },
  { id: 'e42', word: 'Yellow', translation: '黃色', definition: 'The color of a banana.', example: 'The sun is yellow.', level: 'Elementary' },
  { id: 'e43', word: 'Ball', translation: '球', definition: 'A round object for playing.', example: 'Kick the ball to me.', level: 'Elementary' },
  { id: 'e44', word: 'Chair', translation: '椅子', definition: 'Something to sit on.', example: 'Sit on the chair.', level: 'Elementary' },
  { id: 'e45', word: 'Desk', translation: '書桌', definition: 'A table for working.', example: 'My book is on the desk.', level: 'Elementary' },
  { id: 'e46', word: 'Eye', translation: '眼睛', definition: 'Part of the body for seeing.', example: 'Close your eyes.', level: 'Elementary' },
  { id: 'e47', word: 'Foot', translation: '腳', definition: 'Part of the body at the end of the leg.', example: 'My left foot hurts.', level: 'Elementary' },
  { id: 'e48', word: 'Hat', translation: '帽子', definition: 'Something to wear on the head.', example: 'I like your new hat.', level: 'Elementary' },
  { id: 'e49', word: 'Key', translation: '鑰匙', definition: 'Metal tool to open locks.', example: 'I lost my house key.', level: 'Elementary' },
  { id: 'e50', word: 'Leaf', translation: '葉子', definition: 'Green part of a plant.', example: 'The leaf fell down.', level: 'Elementary' },
  { id: 'e51', word: 'Mouth', translation: '嘴巴', definition: 'Part of the face used for eating.', example: 'Open your mouth.', level: 'Elementary' },
  { id: 'e52', word: 'Note', translation: '筆記/便條', definition: 'A short written message.', example: 'Write a note to me.', level: 'Elementary' },
  { id: 'e53', word: 'Paper', translation: '紙', definition: 'Material for writing on.', example: 'I need a piece of paper.', level: 'Elementary' },
  { id: 'e54', word: 'Red', translation: '紅色', definition: 'The color of blood.', example: 'The rose is red.', level: 'Elementary' },
  { id: 'e55', word: 'Ship', translation: '船', definition: 'A large boat.', example: 'The ship is in the sea.', level: 'Elementary' },
  { id: 'e56', word: 'Toy', translation: '玩具', definition: 'Something to play with.', example: 'Where is my toy car?', level: 'Elementary' },
  { id: 'e57', word: 'Up', translation: '向上', definition: 'To a higher place.', example: 'Look up at the sky.', level: 'Elementary' },
  { id: 'e58', word: 'Voice', translation: '聲音', definition: 'Sound made by speaking.', example: 'She has a sweet voice.', level: 'Elementary' },
  { id: 'e59', word: 'Window', translation: '窗戶', definition: 'Glass opening in a wall.', example: 'Look out the window.', level: 'Elementary' },
  { id: 'e60', word: 'Box', translation: '盒子', definition: 'A square container.', example: 'Put it in the box.', level: 'Elementary' },
  { id: 'e61', word: 'Pen', translation: '原子筆', definition: 'Tool for writing with ink.', example: 'Can I use your pen?', level: 'Elementary' },
  { id: 'e62', word: 'Wall', translation: '牆壁', definition: 'Side of a room.', example: 'The wall is white.', level: 'Elementary' },
  { id: 'e63', word: 'Sing', translation: '唱歌', definition: 'To make musical sounds.', example: 'I like to sing.', level: 'Elementary' },
  { id: 'e64', word: 'Blue', translation: '藍色', definition: 'The color of the sky.', example: 'The sky is blue.', level: 'Elementary' },
  { id: 'e65', word: 'Green', translation: '綠色', definition: 'The color of grass.', example: 'The grass is green.', level: 'Elementary' },
  { id: 'e66', word: 'Ear', translation: '耳朵', definition: 'Body part for hearing.', example: 'He has big ears.', level: 'Elementary' },
  { id: 'e67', word: 'Big', translation: '大的', definition: 'Large in size.', example: 'This is a big house.', level: 'Elementary' },
  { id: 'e68', word: 'Small', translation: '小的', definition: 'Little in size.', example: 'A small ant.', level: 'Elementary' },
  { id: 'e69', word: 'Old', translation: '老的', definition: 'Not young.', example: 'My grandpa is old.', level: 'Elementary' },
  { id: 'e70', word: 'New', translation: '新的', definition: 'Not old.', example: 'I have new shoes.', level: 'Elementary' },
  { id: 'e71', word: 'Hot', translation: '熱的', definition: 'High temperature.', example: 'The soup is hot.', level: 'Elementary' },
  { id: 'e72', word: 'Cold', translation: '冷的', definition: 'Low temperature.', example: 'It is cold in winter.', level: 'Elementary' },
  { id: 'e73', word: 'Long', translation: '長的', definition: 'Great in length.', example: 'A long snake.', level: 'Elementary' },
  { id: 'e74', word: 'Short', translation: '短的', definition: 'Not long.', example: 'Short hair.', level: 'Elementary' },
  { id: 'e75', word: 'Good', translation: '好的', definition: 'High quality.', example: 'A good boy.', level: 'Elementary' },
  { id: 'e76', word: 'Bad', translation: '壞的', definition: 'Not good.', example: 'A bad habit.', level: 'Elementary' },
  { id: 'e77', word: 'Fat', translation: '胖的', definition: 'Heavy in weight.', example: 'A fat cat.', level: 'Elementary' },
  { id: 'e78', word: 'Thin', translation: '瘦的', definition: 'Not fat.', example: 'A thin man.', level: 'Elementary' },
  { id: 'e79', word: 'Fast', translation: '快的', definition: 'Quick speed.', example: 'A fast car.', level: 'Elementary' },
  { id: 'e80', word: 'Slow', translation: '慢的', definition: 'Not fast.', example: 'A slow turtle.', level: 'Elementary' },
  { id: 'e81', word: 'Run', translation: '跑', definition: 'To move fast.', example: 'Run to school.', level: 'Elementary' },
  { id: 'e82', word: 'Walk', translation: '走', definition: 'To move by feet.', example: 'Walk slowly.', level: 'Elementary' },
  { id: 'e83', word: 'Swim', translation: '游泳', definition: 'To move in water.', example: 'I can swim.', level: 'Elementary' },
  { id: 'e84', word: 'Read', translation: '讀', definition: 'To look at words.', example: 'Read a book.', level: 'Elementary' },
  { id: 'e85', word: 'Write', translation: '寫', definition: 'To make marks.', example: 'Write your name.', level: 'Elementary' },
  { id: 'e86', word: 'Cook', translation: '煮', definition: 'To make food.', example: 'Mom can cook.', level: 'Elementary' },
  { id: 'e87', word: 'Wash', translation: '洗', definition: 'To clean with water.', example: 'Wash your hands.', level: 'Elementary' },
  { id: 'e88', word: 'Sleep', translation: '睡', definition: 'To rest at night.', example: 'Sleep tight.', level: 'Elementary' },
  { id: 'e89', word: 'Talk', translation: '談話', definition: 'To speak.', example: 'Talk to me.', level: 'Elementary' },
  { id: 'e90', word: 'Listen', translation: '聽', definition: 'To pay attention to sound.', example: 'Listen to music.', level: 'Elementary' },
  { id: 'e91', word: 'Brother', translation: '兄弟', definition: 'Male sibling.', example: 'I have a brother.', level: 'Elementary' },
  { id: 'e92', word: 'Sister', translation: '姊妹', definition: 'Female sibling.', example: 'My sister is kind.', level: 'Elementary' },
  { id: 'e93', word: 'Father', translation: '父親', definition: 'Male parent.', example: 'My father is tall.', level: 'Elementary' },
  { id: 'e94', word: 'Mother', translation: '母親', definition: 'Female parent.', example: 'I love my mother.', level: 'Elementary' },
  { id: 'e95', word: 'Teacher', translation: '老師', definition: 'Person who teaches.', example: 'She is a teacher.', level: 'Elementary' },
  { id: 'e96', word: 'Student', translation: '學生', definition: 'Person who learns.', example: 'I am a student.', level: 'Elementary' },
  { id: 'e97', word: 'School', translation: '學校', definition: 'Place to learn.', example: 'Go to school.', level: 'Elementary' },
  { id: 'e98', word: 'Table', translation: '桌子', definition: 'Flat furniture.', example: 'On the table.', level: 'Elementary' },
  { id: 'e99', word: 'Face', translation: '臉', definition: 'Front of head.', example: 'Wash your face.', level: 'Elementary' },
  { id: 'e100', word: 'Hair', translation: '頭髮', definition: 'Thing on head.', example: 'Black hair.', level: 'Elementary' },
  { id: 'e101', word: 'About', translation: '關於', definition: 'On the subject of.', example: 'Tell me about your day.', level: 'Elementary' },
  { id: 'e102', word: 'After', translation: '在...之後', definition: 'Later than something.', example: 'We play after lunch.', level: 'Elementary' },
  { id: 'e103', word: 'Again', translation: '再次', definition: 'One more time.', example: 'Try it again.', level: 'Elementary' },
  { id: 'e104', word: 'All', translation: '全部', definition: 'The whole number.', example: 'All the students are here.', level: 'Elementary' },
  { id: 'e105', word: 'Always', translation: '總是', definition: 'At all times.', example: 'I always brush my teeth.', level: 'Elementary' },
  { id: 'e106', word: 'Animal', translation: '動物', definition: 'A living creature.', example: 'The tiger is a wild animal.', level: 'Elementary' },
  { id: 'e107', word: 'Another', translation: '另一個', definition: 'One more of the same.', example: 'I want another cookie.', level: 'Elementary' },
  { id: 'e108', word: 'Answer', translation: '回答', definition: 'Reaction to a question.', example: 'What is the answer?', level: 'Elementary' },
  { id: 'e109', word: 'Any', translation: '任何', definition: 'One or some.', example: 'Do you have any pets?', level: 'Elementary' },
  { id: 'e110', word: 'Ask', translation: '詢問', definition: 'To request information.', example: 'Ask your teacher.', level: 'Elementary' },
  { id: 'e111', word: 'Back', translation: '背部/後面', definition: 'Rear part.', example: 'My back hurts.', level: 'Elementary' },
  { id: 'e112', word: 'Before', translation: '在...之前', definition: 'Earlier than.', example: 'Wash hands before eating.', level: 'Elementary' },
  { id: 'e113', word: 'Best', translation: '最好的', definition: 'Of highest quality.', example: 'You are my best friend.', level: 'Elementary' },
  { id: 'e114', word: 'Better', translation: '較好的', definition: 'More excellent.', example: 'I feel better today.', level: 'Elementary' },
  { id: 'e115', word: 'Bird', translation: '鳥', definition: 'Animal with feathers.', example: 'The bird is singing.', level: 'Elementary' },
  { id: 'e116', word: 'Black', translation: '黑色', definition: 'Darkest color.', example: 'I have black shoes.', level: 'Elementary' },
  { id: 'e117', word: 'Boat', translation: '小船', definition: 'Small vessel.', example: 'Row the boat.', level: 'Elementary' },
  { id: 'e118', word: 'Both', translation: '兩者都', definition: 'Two together.', example: 'Both of us like pizza.', level: 'Elementary' },
  { id: 'e119', word: 'Boy', translation: '男孩', definition: 'Male child.', example: 'The boy is tall.', level: 'Elementary' },
  { id: 'e120', word: 'Bring', translation: '帶來', definition: 'To take along.', example: 'Bring your umbrella.', level: 'Elementary' },
  { id: 'e121', word: 'Call', translation: '呼叫', definition: 'To speak loudly.', example: 'Call my name.', level: 'Elementary' },
  { id: 'e122', word: 'Came', translation: '來(過去式)', definition: 'Arrived.', example: 'He came to my house.', level: 'Elementary' },
  { id: 'e123', word: 'Can', translation: '能/罐子', definition: 'Able to.', example: 'I can swim.', level: 'Elementary' },
  { id: 'e124', word: 'Car', translation: '汽車', definition: 'Motor vehicle.', example: 'Drive the car.', level: 'Elementary' },
  { id: 'e125', word: 'Care', translation: '照顧', definition: 'To look after.', example: 'Take care of yourself.', level: 'Elementary' },
  { id: 'e126', word: 'Carry', translation: '搬運', definition: 'To take from one place to another.', example: 'Carry the bag.', level: 'Elementary' },
  { id: 'e127', word: 'Change', translation: '改變/零錢', definition: 'To make different.', example: 'The weather will change.', level: 'Elementary' },
  { id: 'e128', word: 'Child', translation: '小孩', definition: 'Young human.', example: 'A happy child.', level: 'Elementary' },
  { id: 'e129', word: 'City', translation: '城市', definition: 'Large town.', example: 'Taipei is a big city.', level: 'Elementary' },
  { id: 'e130', word: 'Clean', translation: '乾淨的', definition: 'Not dirty.', example: 'Keep your room clean.', level: 'Elementary' },
  { id: 'e131', word: 'Close', translation: '關閉/親近', definition: 'To shut.', example: 'Close the door.', level: 'Elementary' },
  { id: 'e132', word: 'Color', translation: '顏色', definition: 'Hue or tint.', example: 'Red is a color.', level: 'Elementary' },
  { id: 'e133', word: 'Come', translation: '來', definition: 'To move toward.', example: 'Come here.', level: 'Elementary' },
  { id: 'e134', word: 'Could', translation: '可以(助動詞)', definition: 'Past of can.', example: 'I could swim when I was five.', level: 'Elementary' },
  { id: 'e135', word: 'Country', translation: '國家/鄉村', definition: 'Nation.', example: 'Taiwan is a country.', level: 'Elementary' },
  { id: 'e136', word: 'Cut', translation: '切', definition: 'To use scissors.', example: 'Cut the paper.', level: 'Elementary' },
  { id: 'e137', word: 'Day', translation: '日子', definition: 'Time from sunrise to sunset.', example: 'Have a nice day.', level: 'Elementary' },
  { id: 'e138', word: 'Did', translation: '做(過去式)', definition: 'Performed.', example: 'I did my homework.', level: 'Elementary' },
  { id: 'e139', word: 'Different', translation: '不同的', definition: 'Not the same.', example: 'We are all different.', level: 'Elementary' },
  { id: 'e140', word: 'Does', translation: '做(單數現在式)', definition: 'Performs.', example: 'He does his work.', level: 'Elementary' },
  { id: 'e141', word: 'Done', translation: '已完成的', definition: 'Finished.', example: 'Is it done?', level: 'Elementary' },
  { id: 'e142', word: 'Down', translation: '向下', definition: 'To a lower place.', example: 'Sit down.', level: 'Elementary' },
  { id: 'e143', word: 'Draw', translation: '畫', definition: 'To make pictures.', example: 'Draw a circle.', level: 'Elementary' },
  { id: 'e144', word: 'Drink', translation: '喝', definition: 'To swallow liquid.', example: 'Drink some water.', level: 'Elementary' },
  { id: 'e145', word: 'Each', translation: '每個', definition: 'Every one.', example: 'Each student has a pen.', level: 'Elementary' },
  { id: 'e146', word: 'Earth', translation: '地球/泥土', definition: 'Our planet.', example: 'Protect the earth.', level: 'Elementary' },
  { id: 'e147', word: 'End', translation: '結束', definition: 'The final part.', example: 'The story has an end.', level: 'Elementary' },
  { id: 'e148', word: 'Enough', translation: '足夠的', definition: 'As much as needed.', example: 'I have enough food.', level: 'Elementary' },
  { id: 'e149', word: 'Even', translation: '甚至/平坦的', definition: 'Used for emphasis.', example: 'He didn\'t even say hi.', level: 'Elementary' },
  { id: 'e150', word: 'Ever', translation: '曾經', definition: 'At any time.', example: 'Have you ever been there?', level: 'Elementary' },
  { id: 'e151', word: 'Every', translation: '每個', definition: 'Each one.', example: 'I go every day.', level: 'Elementary' },
  { id: 'e152', word: 'Fall', translation: '落下/秋天', definition: 'To drop down.', example: 'Leaves fall in autumn.', level: 'Elementary' },
  { id: 'e153', word: 'Far', translation: '遠的', definition: 'A long distance.', example: 'Is it far?', level: 'Elementary' },
  { id: 'e154', word: 'Feel', translation: '感覺', definition: 'To experience emotion.', example: 'I feel happy.', level: 'Elementary' },
  { id: 'e155', word: 'Few', translation: '少的', definition: 'Not many.', example: 'I have a few friends.', level: 'Elementary' },
  { id: 'e156', word: 'Find', translation: '尋找', definition: 'To locate.', example: 'Can you find it?', level: 'Elementary' },
  { id: 'e157', word: 'First', translation: '第一', definition: 'Coming before all others.', example: 'First things first.', level: 'Elementary' },
  { id: 'e158', word: 'Five', translation: '五', definition: 'Number after four.', example: 'I have five fingers.', level: 'Elementary' },
  { id: 'e159', word: 'Fly', translation: '飛/蒼蠅', definition: 'To move in air.', example: 'Birds can fly.', level: 'Elementary' },
  { id: 'e160', word: 'Food', translation: '食物', definition: 'Things we eat.', example: 'Healthy food.', level: 'Elementary' },
  { id: 'e161', word: 'Form', translation: '表格/形式', definition: 'Shape or document.', example: 'Fill out this form.', level: 'Elementary' },
  { id: 'e162', word: 'Found', translation: '找到(過去式)', definition: 'Located.', example: 'I found my keys.', level: 'Elementary' },
  { id: 'e163', word: 'Four', translation: '四', definition: 'Number after three.', example: 'A dog has four legs.', level: 'Elementary' },
  { id: 'e164', word: 'From', translation: '來自', definition: 'Starting point.', example: 'Where are you from?', level: 'Elementary' },
  { id: 'e165', word: 'Full', translation: '滿的', definition: 'Holding as much as possible.', example: 'The glass is full.', level: 'Elementary' },
  { id: 'e166', word: 'Gave', translation: '給(過去式)', definition: 'Offered.', example: 'He gave me a book.', level: 'Elementary' },
  { id: 'e167', word: 'Get', translation: '得到', definition: 'To receive.', example: 'Get some sleep.', level: 'Elementary' },
  { id: 'e168', word: 'Give', translation: '給', definition: 'To offer.', example: 'Give me a hand.', level: 'Elementary' },
  { id: 'e169', word: 'Great', translation: '偉大的', definition: 'Very good.', example: 'Have a great day.', level: 'Elementary' },
  { id: 'e170', word: 'Grow', translation: '成長', definition: 'To increase in size.', example: 'Plants grow fast.', level: 'Elementary' },
  { id: 'e171', word: 'Had', translation: '有(過去式)', definition: 'Possessed.', example: 'I had a cat.', level: 'Elementary' },
  { id: 'e172', word: 'Hard', translation: '硬的/困難的', definition: 'Not soft.', example: 'This is hard work.', level: 'Elementary' },
  { id: 'e173', word: 'Has', translation: '有(單數現在式)', definition: 'Possesses.', example: 'He has a ball.', level: 'Elementary' },
  { id: 'e174', word: 'Have', translation: '有', definition: 'To possess.', example: 'I have a pen.', level: 'Elementary' },
  { id: 'e175', word: 'He', translation: '他', definition: 'Male person.', example: 'He is nice.', level: 'Elementary' },
  { id: 'e176', word: 'Head', translation: '頭部', definition: 'Part of body.', example: 'My head hurts.', level: 'Elementary' },
  { id: 'e177', word: 'Hear', translation: '聽見', definition: 'To listen with ears.', example: 'I hear you.', level: 'Elementary' },
  { id: 'e178', word: 'Help', translation: '幫助', definition: 'To assist.', example: 'Can you help me?', level: 'Elementary' },
  { id: 'e179', word: 'Her', translation: '她的', definition: 'Belonging to female.', example: 'This is her bag.', level: 'Elementary' },
  { id: 'e180', word: 'Here', translation: '這裡', definition: 'In this place.', example: 'Come here.', level: 'Elementary' },
  { id: 'e181', word: 'High', translation: '高的', definition: 'Up above.', example: 'The mountain is high.', level: 'Elementary' },
  { id: 'e182', word: 'Him', translation: '他(受格)', definition: 'Male object.', example: 'I saw him.', level: 'Elementary' },
  { id: 'e183', word: 'His', translation: '他的', definition: 'Belonging to male.', example: 'This is his car.', level: 'Elementary' },
  { id: 'e184', word: 'Hold', translation: '握住', definition: 'To grip.', example: 'Hold my hand.', level: 'Elementary' },
  { id: 'e185', word: 'House', translation: '房子', definition: 'Building to live in.', example: 'This is my house.', level: 'Elementary' },
  { id: 'e186', word: 'How', translation: '如何', definition: 'In what way.', example: 'How are you?', level: 'Elementary' },
  { id: 'e187', word: 'If', translation: '如果', definition: 'In case that.', example: 'If it rains, stay home.', level: 'Elementary' },
  { id: 'e188', word: 'Important', translation: '重要的', definition: 'Significant.', example: 'This is important.', level: 'Elementary' },
  { id: 'e189', word: 'Into', translation: '進入', definition: 'To the inside.', example: 'Go into the room.', level: 'Elementary' },
  { id: 'e190', word: 'Just', translation: '剛才/公平的', definition: 'Only or recently.', example: 'I just ate.', level: 'Elementary' },
  { id: 'e191', word: 'Keep', translation: '保持', definition: 'To retain.', example: 'Keep the change.', level: 'Elementary' },
  { id: 'e192', word: 'Kind', translation: '親切的/種類', definition: 'Nice or type.', example: 'Be kind to others.', level: 'Elementary' },
  { id: 'e193', word: 'Know', translation: '知道', definition: 'To understand.', example: 'I know the answer.', level: 'Elementary' },
  { id: 'e194', word: 'Land', translation: '土地/降落', definition: 'Ground.', example: 'Dry land.', level: 'Elementary' },
  { id: 'e195', word: 'Large', translation: '大的', definition: 'Big.', example: 'A large pizza.', level: 'Elementary' },
  { id: 'e196', word: 'Last', translation: '最後的/持續', definition: 'After all others.', example: 'The last one.', level: 'Elementary' },
  { id: 'e197', word: 'Later', translation: '稍後', definition: 'Afterwards.', example: 'See you later.', level: 'Elementary' },
  { id: 'e198', word: 'Learn', translation: '學習', definition: 'To get knowledge.', example: 'Learn English.', level: 'Elementary' },
  { id: 'e199', word: 'Letter', translation: '信件/字母', definition: 'Written message.', example: 'Write a letter.', level: 'Elementary' },
  { id: 'e200', word: 'Life', translation: '生命', definition: 'Existence.', example: 'Life is beautiful.', level: 'Elementary' },
  { id: 'e201', word: 'Light', translation: '光/輕的', definition: 'Opposite of dark.', example: 'Turn on the light.', level: 'Elementary' },
  { id: 'e202', word: 'Like', translation: '喜歡/像', definition: 'To enjoy.', example: 'I like apples.', level: 'Elementary' },
  { id: 'e203', word: 'Line', translation: '線條/隊伍', definition: 'Long mark.', example: 'Draw a line.', level: 'Elementary' },
  { id: 'e204', word: 'Little', translation: '小的/少的', definition: 'Small.', example: 'A little puppy.', level: 'Elementary' },
  { id: 'e205', word: 'Live', translation: '生活/居住', definition: 'To exist.', example: 'Where do you live?', level: 'Elementary' },
  { id: 'e206', word: 'Look', translation: '看', definition: 'To use eyes.', example: 'Look at me.', level: 'Elementary' },
  { id: 'e207', word: 'Love', translation: '愛', definition: 'Deep affection.', example: 'I love mom.', level: 'Elementary' },
  { id: 'e208', word: 'Made', translation: '做(過去式)', definition: 'Created.', example: 'He made a cake.', level: 'Elementary' },
  { id: 'e209', word: 'Make', translation: '做', definition: 'To create.', example: 'Make a wish.', level: 'Elementary' },
  { id: 'e210', word: 'Many', translation: '許多的', definition: 'A large number.', example: 'Many people.', level: 'Elementary' },
  { id: 'e211', word: 'May', translation: '可能/五月', definition: 'Perhaps.', example: 'It may rain.', level: 'Elementary' },
  { id: 'e212', word: 'Me', translation: '我(受格)', definition: 'Myself.', example: 'Tell me.', level: 'Elementary' },
  { id: 'e213', word: 'Mean', translation: '意思/刻薄的', definition: 'To signify.', example: 'What does it mean?', level: 'Elementary' },
  { id: 'e214', word: 'Men', translation: '男人(複數)', definition: 'Adult males.', example: 'The men are tall.', level: 'Elementary' },
  { id: 'e215', word: 'Might', translation: '可能', definition: 'Perhaps.', example: 'He might come.', level: 'Elementary' },
  { id: 'e216', word: 'Mile', translation: '英哩', definition: 'Unit of distance.', example: 'A long mile.', level: 'Elementary' },
  { id: 'e217', word: 'More', translation: '更多', definition: 'Greater amount.', example: 'I want more.', level: 'Elementary' },
  { id: 'e218', word: 'Most', translation: '最多的', definition: 'Greatest amount.', example: 'Most of them.', level: 'Elementary' },
  { id: 'e219', word: 'Mr.', translation: '先生', definition: 'Title for a man.', example: 'Mr. Wang.', level: 'Elementary' },
  { id: 'e220', word: 'Must', translation: '必須', definition: 'Necessary.', example: 'You must go.', level: 'Elementary' },
  { id: 'e221', word: 'My', translation: '我的', definition: 'Belonging to me.', example: 'My house.', level: 'Elementary' },
  { id: 'e222', word: 'Name', translation: '名字', definition: 'What something is called.', example: 'What is your name?', level: 'Elementary' },
  { id: 'e223', word: 'Near', translation: '近的', definition: 'Close to.', example: 'I live near here.', level: 'Elementary' },
  { id: 'e224', word: 'Never', translation: '從不', definition: 'At no time.', example: 'I never lie.', level: 'Elementary' },
  { id: 'e225', word: 'Next', translation: '下一個', definition: 'Following after.', example: 'Next week.', level: 'Elementary' },
  { id: 'e226', word: 'No', translation: '不', definition: 'Negative.', example: 'No, thank you.', level: 'Elementary' },
  { id: 'e227', word: 'Now', translation: '現在', definition: 'At this moment.', example: 'Do it now.', level: 'Elementary' },
  { id: 'e228', word: 'Number', translation: '數字', definition: 'Numeral.', example: 'A phone number.', level: 'Elementary' },
  { id: 'e229', word: 'Off', translation: '離開/關閉', definition: 'Away from.', example: 'Turn off the TV.', level: 'Elementary' },
  { id: 'e230', word: 'Often', translation: '經常', definition: 'Frequently.', example: 'I often go there.', level: 'Elementary' },
  { id: 'e231', word: 'On', translation: '在...之上', definition: 'Above.', example: 'On the table.', level: 'Elementary' },
  { id: 'e232', word: 'One', translation: '一', definition: 'The number 1.', example: 'I have one sister.', level: 'Elementary' },
  { id: 'e233', word: 'Only', translation: '只有', definition: 'No others.', example: 'I only have one dollar.', level: 'Elementary' },
  { id: 'e234', word: 'Or', translation: '或者', definition: 'Choice.', example: 'Tea or coffee?', level: 'Elementary' },
  { id: 'e235', word: 'Other', translation: '其他的', definition: 'Remaining.', example: 'The other side.', level: 'Elementary' },
  { id: 'e236', word: 'Our', translation: '我們的', definition: 'Belonging to us.', example: 'Our home.', level: 'Elementary' },
  { id: 'e237', word: 'Out', translation: '外面', definition: 'External.', example: 'Go out.', level: 'Elementary' },
  { id: 'e238', word: 'Over', translation: '上方/結束', definition: 'Above.', example: 'Jump over.', level: 'Elementary' },
  { id: 'e239', word: 'Own', translation: '自己的', definition: 'Personal.', example: 'My own car.', level: 'Elementary' },
  { id: 'e240', word: 'Part', translation: '部分', definition: 'A piece.', example: 'Part of the plan.', level: 'Elementary' },
  { id: 'e241', word: 'People', translation: '人們', definition: 'Humans.', example: 'Many people.', level: 'Elementary' },
  { id: 'e242', word: 'Place', translation: '地方', definition: 'Location.', example: 'A nice place.', level: 'Elementary' },
  { id: 'e243', word: 'Plant', translation: '植物/工廠', definition: 'Green living thing.', example: 'Water the plant.', level: 'Elementary' },
  { id: 'e244', word: 'Play', translation: '玩/演劇', definition: 'Have fun.', example: 'Play soccer.', level: 'Elementary' },
  { id: 'e245', word: 'Point', translation: '點/意義', definition: 'Dot or purpose.', example: 'I get your point.', level: 'Elementary' },
  { id: 'e246', word: 'Put', translation: '放', definition: 'To place.', example: 'Put it down.', level: 'Elementary' },
  { id: 'e247', word: 'Read', translation: '讀', definition: 'To look at words.', example: 'Read aloud.', level: 'Elementary' },
  { id: 'e248', word: 'Right', translation: '正確的/右邊', definition: 'Correct.', example: 'You are right.', level: 'Elementary' },
  { id: 'e249', word: 'River', translation: '河流', definition: 'Stream of water.', example: 'A long river.', level: 'Elementary' },
  { id: 'e250', word: 'Same', translation: '相同的', definition: 'Not different.', example: 'The same color.', level: 'Elementary' },
  { id: 'e251', word: 'Say', translation: '說', definition: 'To speak.', example: 'What did you say?', level: 'Elementary' },
  { id: 'e252', word: 'See', translation: '看見', definition: 'To perceive.', example: 'I see a bird.', level: 'Elementary' },
  { id: 'e253', word: 'Set', translation: '設定/一組', definition: 'To put in place.', example: 'Set the table.', level: 'Elementary' },
  { id: 'e254', word: 'She', translation: '她', definition: 'Female person.', example: 'She is a girl.', level: 'Elementary' },
  { id: 'e255', word: 'Show', translation: '展示', definition: 'To display.', example: 'Show me your toy.', level: 'Elementary' },
  { id: 'e256', word: 'Side', translation: '邊/側面', definition: 'Edge.', example: 'The other side.', level: 'Elementary' },
  { id: 'e257', word: 'Small', translation: '小的', definition: 'Little.', example: 'A small bag.', level: 'Elementary' },
  { id: 'e258', word: 'So', translation: '所以/如此', definition: 'Therefore.', example: 'I am hungry, so I eat.', level: 'Elementary' },
  { id: 'e259', word: 'Some', translation: '一些', definition: 'A portion.', example: 'Have some milk.', level: 'Elementary' },
  { id: 'e260', word: 'Something', translation: '某事', definition: 'A thing.', example: 'I want something to drink.', level: 'Elementary' },
  { id: 'e261', word: 'Sometimes', translation: '有時', definition: 'Occasionally.', example: 'I sometimes run.', level: 'Elementary' },
  { id: 'e262', word: 'Song', translation: '歌曲', definition: 'Musical piece.', example: 'Sing a song.', level: 'Elementary' },
  { id: 'e263', word: 'Sound', translation: '聲音', definition: 'Audio.', example: 'A loud sound.', level: 'Elementary' },
  { id: 'e264', word: 'Stay', translation: '停留', definition: 'To remain.', example: 'Stay here.', level: 'Elementary' },
  { id: 'e265', word: 'Still', translation: '仍然/靜止的', definition: 'Continuing.', example: 'I am still here.', level: 'Elementary' },
  { id: 'e266', word: 'Stop', translation: '停止', definition: 'To end motion.', example: 'Stop the car.', level: 'Elementary' },
  { id: 'e267', word: 'Story', translation: '故事', definition: 'Tale.', example: 'Tell a story.', level: 'Elementary' },
  { id: 'e268', word: 'Study', translation: '學習/研究', definition: 'To learn.', example: 'Study hard.', level: 'Elementary' },
  { id: 'e269', word: 'Such', translation: '如此的', definition: 'Of that kind.', example: 'Such a nice day.', level: 'Elementary' },
  { id: 'e270', word: 'Take', translation: '拿取', definition: 'To get.', example: 'Take it away.', level: 'Elementary' },
  { id: 'e271', word: 'Tell', translation: '告訴', definition: 'To inform.', example: 'Tell me more.', level: 'Elementary' },
  { id: 'e272', word: 'Than', translation: '比', definition: 'Comparison.', example: 'Older than you.', level: 'Elementary' },
  { id: 'e273', word: 'That', translation: '那個', definition: 'Demonstrative.', example: 'That is my house.', level: 'Elementary' },
  { id: 'e274', word: 'The', translation: '這個', definition: 'Article.', example: 'The sun.', level: 'Elementary' },
  { id: 'e275', word: 'Their', translation: '他們的', definition: 'Belonging to them.', example: 'Their toys.', level: 'Elementary' },
  { id: 'e276', word: 'Them', translation: '他們(受格)', definition: 'Object.', example: 'I see them.', level: 'Elementary' },
  { id: 'e277', word: 'Then', translation: '那時/然後', definition: 'At that time.', example: 'Back then.', level: 'Elementary' },
  { id: 'e278', word: 'There', translation: '那裡', definition: 'In that place.', example: 'Over there.', level: 'Elementary' },
  { id: 'e279', word: 'These', translation: '這些', definition: 'Plural of this.', example: 'These apples.', level: 'Elementary' },
  { id: 'e280', word: 'They', translation: '他們', definition: 'Subject.', example: 'They are happy.', level: 'Elementary' },
  { id: 'e281', word: 'Thing', translation: '事物', definition: 'Object.', example: 'One more thing.', level: 'Elementary' },
  { id: 'e282', word: 'Think', translation: '想', definition: 'To believe.', example: 'I think so.', level: 'Elementary' },
  { id: 'e283', word: 'This', translation: '這個', definition: 'Demonstrative.', example: 'This is my book.', level: 'Elementary' },
  { id: 'e284', word: 'Those', translation: '那些', definition: 'Plural of that.', example: 'Those clouds.', level: 'Elementary' },
  { id: 'e285', word: 'Thought', translation: '想法/想(過去式)', definition: 'Idea.', example: 'A good thought.', level: 'Elementary' },
  { id: 'e286', word: 'Three', translation: '三', definition: 'Number.', example: 'Three birds.', level: 'Elementary' },
  { id: 'e287', word: 'Through', translation: '穿過', definition: 'In and out.', example: 'Through the tunnel.', level: 'Elementary' },
  { id: 'e288', word: 'Time', translation: '時間', definition: 'Duration.', example: 'What time is it?', level: 'Elementary' },
  { id: 'e289', word: 'To', translation: '到/向', definition: 'Direction.', example: 'Go to school.', level: 'Elementary' },
  { id: 'e290', word: 'Together', translation: '一起', definition: 'In a group.', example: 'Play together.', level: 'Elementary' },
  { id: 'e291', word: 'Too', translation: '太/也', definition: 'Also.', example: 'Me too.', level: 'Elementary' },
  { id: 'e292', word: 'Took', translation: '拿(過去式)', definition: 'Received.', example: 'He took my pen.', level: 'Elementary' },
  { id: 'e293', word: 'Two', translation: '二', definition: 'Number.', example: 'Two eyes.', level: 'Elementary' },
  { id: 'e294', word: 'Under', translation: '在...之下', definition: 'Below.', example: 'Under the tree.', level: 'Elementary' },
  { id: 'e295', word: 'Until', translation: '直到', definition: 'Up to.', example: 'Stay until dark.', level: 'Elementary' },
  { id: 'e296', word: 'Up', translation: '向上', definition: 'To a higher place.', example: 'Get up.', level: 'Elementary' },
  { id: 'e297', word: 'Us', translation: '我們(受格)', definition: 'Myself and others.', example: 'Help us.', level: 'Elementary' },
  { id: 'e298', word: 'Use', translation: '使用', definition: 'Utilize.', example: 'Use a pen.', level: 'Elementary' },
  { id: 'e299', word: 'Very', translation: '非常', definition: 'Highly.', example: 'Very good.', level: 'Elementary' },
  { id: 'e300', word: 'Walk', translation: '走', definition: 'Move by feet.', example: 'Walk slowly.', level: 'Elementary' },
];
