import { VocabWord } from "../vocab-data";

export const ELEMENTARY_VOCAB: VocabWord[] = [
  { id: 'e1', word: 'Apple', translation: '蘋果', definition: 'A round fruit with red or green skin.', example: 'I eat an apple every day.', level: 'Elementary' },
  { id: 'e2', word: 'Book', translation: '書', definition: 'A set of printed pages fastened together.', example: 'He is reading a story book.', level: 'Elementary' },
  { id: 'e3', word: 'Cat', translation: '貓', definition: 'A small animal with fur and a tail.', example: 'My cat is sleeping on the sofa.', level: 'Elementary' },
  { id: 'e4', word: 'Dog', translation: '狗', definition: 'A common animal often kept as a pet.', example: 'The dog is barking at the stranger.', level: 'Elementary' },
  { id: 'e5', word: 'Eat', translation: '吃', definition: 'To put food into your mouth and swallow it.', example: 'What do you want to eat for lunch?', level: 'Elementary' },
  { id: 'e6', word: 'Fish', translation: '魚', definition: 'An animal that lives in water.', example: 'There are many fish in the pond.', level: 'Elementary' },
  { id: 'e7', word: 'Go', translation: '去', definition: 'To move or travel to a place.', example: 'I go to school by bus.', level: 'Elementary' },
  { id: 'e8', word: 'Happy', translation: '快樂的', definition: 'Feeling or showing pleasure.', example: 'She is happy because she won the game.', level: 'Elementary' },
  { id: 'e9', word: 'Ice', translation: '冰', definition: 'Water that has frozen solid.', example: 'I like my juice with ice.', level: 'Elementary' },
  { id: 'e10', word: 'Jump', translation: '跳', definition: 'To push yourself off the ground.', example: 'The kids love to jump on the bed.', level: 'Elementary' },
  { id: 'e11', word: 'Key', translation: '鑰匙', definition: 'A small piece of metal used to open a lock.', example: 'I lost my house key.', level: 'Elementary' },
  { id: 'e12', word: 'Lion', translation: '獅子', definition: 'A large wild cat that lives in Africa.', example: 'The lion is the king of the jungle.', level: 'Elementary' },
  { id: 'e13', word: 'Milk', translation: '牛奶', definition: 'A white liquid produced by cows.', example: 'I drink milk every morning.', level: 'Elementary' },
  { id: 'e14', word: 'Night', translation: '夜晚', definition: 'The time when it is dark outside.', example: 'The stars shine at night.', level: 'Elementary' },
  { id: 'e15', word: 'Orange', translation: '橘子', definition: 'A round orange fruit.', example: 'Would you like an orange?', level: 'Elementary' },
  { id: 'e16', word: 'Pen', translation: '鋼筆', definition: 'An instrument used for writing with ink.', example: 'Can I borrow your pen?', level: 'Elementary' },
  { id: 'e17', word: 'Queen', translation: '皇后', definition: 'A female ruler of a country.', example: 'The queen lives in a palace.', level: 'Elementary' },
  { id: 'e18', word: 'Rain', translation: '雨', definition: 'Water that falls from the sky.', example: 'I love the smell of rain.', level: 'Elementary' },
  { id: 'e19', word: 'Sun', translation: '太陽', definition: 'The star that gives light and heat to the Earth.', example: 'The sun rises in the east.', level: 'Elementary' },
  { id: 'e20', word: 'Tree', translation: '樹', definition: 'A tall plant with a wooden trunk.', example: 'The tree has green leaves.', level: 'Elementary' },
  { id: 'e21', word: 'Umbrella', translation: '雨傘', definition: 'Used to keep you dry when it rains.', example: 'Don\'t forget your umbrella.', level: 'Elementary' },
  { id: 'e22', word: 'Van', translation: '貨車', definition: 'A medium-sized vehicle used for moving goods.', example: 'He drives a white van.', level: 'Elementary' },
  { id: 'e23', word: 'Water', translation: '水', definition: 'A clear liquid without color or taste.', example: 'Please give me some water.', level: 'Elementary' },
  { id: 'e24', word: 'Xylophone', translation: '木琴', definition: 'A musical instrument with wooden bars.', example: 'She plays the xylophone very well.', level: 'Elementary' },
  { id: 'e25', word: 'Yellow', translation: '黃色', definition: 'A color like the sun.', example: 'The banana is yellow.', level: 'Elementary' },
  { id: 'e26', word: 'Zebra', translation: '斑馬', definition: 'An animal with black and white stripes.', example: 'A zebra looks like a horse.', level: 'Elementary' },
  { id: 'e27', word: 'Bread', translation: '麵包', definition: 'Food made from flour and water.', example: 'I had bread for breakfast.', level: 'Elementary' },
  { id: 'e28', word: 'Chair', translation: '椅子', definition: 'Something you sit on.', example: 'Please sit on the chair.', level: 'Elementary' },
  { id: 'e29', word: 'Duck', translation: '鴨子', definition: 'A bird that swims in water.', example: 'The duck is swimming in the pond.', level: 'Elementary' },
  { id: 'e30', word: 'Egg', translation: '蛋', definition: 'An oval object laid by a bird.', example: 'I like boiled eggs.', level: 'Elementary' },
  { id: 'e31', word: 'Friend', translation: '朋友', definition: 'Someone you know and like.', example: 'She is my best friend.', level: 'Elementary' },
  { id: 'e32', word: 'Girl', translation: '女孩', definition: 'A female child.', example: 'The girl is wearing a red dress.', level: 'Elementary' },
  { id: 'e33', word: 'House', translation: '房子', definition: 'A building where people live.', example: 'This is my house.', level: 'Elementary' },
  { id: 'e34', word: 'Juice', translation: '果汁', definition: 'Liquid from fruit or vegetables.', example: 'I want some apple juice.', level: 'Elementary' },
  { id: 'e35', word: 'Kite', translation: '風箏', definition: 'A toy that flies in the wind.', example: 'He is flying a kite.', level: 'Elementary' },
  { id: 'e36', word: 'Lamp', translation: '燈', definition: 'Something that gives light.', example: 'Turn on the lamp.', level: 'Elementary' },
  { id: 'e37', word: 'Moon', translation: '月亮', definition: 'The round object that shines in the night sky.', example: 'The moon is very bright tonight.', level: 'Elementary' },
  { id: 'e38', word: 'Nose', translation: '鼻子', definition: 'The part of your face used for smelling.', example: 'He has a small nose.', level: 'Elementary' },
  { id: 'e39', word: 'Owl', translation: '貓頭鷹', definition: 'A bird that is active at night.', example: 'The owl is hooting.', level: 'Elementary' },
  { id: 'e40', word: 'Pig', translation: '豬', definition: 'A pink animal that lives on a farm.', example: 'The pig is very fat.', level: 'Elementary' },
  { id: 'e41', word: 'Quiet', translation: '安靜的', definition: 'Making very little noise.', example: 'Please be quiet in the library.', level: 'Elementary' },
  { id: 'e42', word: 'Rabbit', translation: '兔子', definition: 'A small animal with long ears.', example: 'The rabbit is eating a carrot.', level: 'Elementary' },
  { id: 'e43', word: 'Star', translation: '星星', definition: 'A bright point in the night sky.', example: 'I can see a star.', level: 'Elementary' },
  { id: 'e44', word: 'Train', translation: '火車', definition: 'A long vehicle that runs on tracks.', example: 'The train is arriving.', level: 'Elementary' },
  { id: 'e45', word: 'Up', translation: '向上', definition: 'Moving towards a higher position.', example: 'Look up at the sky.', level: 'Elementary' },
  { id: 'e46', word: 'Voice', translation: '聲音', definition: 'The sound you make when you speak.', example: 'She has a beautiful voice.', level: 'Elementary' },
  { id: 'e47', word: 'Wind', translation: '風', definition: 'Moving air.', example: 'The wind is blowing hard.', level: 'Elementary' },
  { id: 'e48', word: 'Box', translation: '盒子', definition: 'A container with flat sides.', example: 'Put the toys in the box.', level: 'Elementary' },
  { id: 'e49', word: 'Yacht', translation: '遊艇', definition: 'A large boat used for pleasure.', example: 'They have a big yacht.', level: 'Elementary' },
  { id: 'e50', word: 'Zoo', translation: '動物園', definition: 'A place where wild animals are kept.', example: 'Let\'s go to the zoo.', level: 'Elementary' },
  { id: 'e51', word: 'Ant', translation: '螞蟻', definition: 'A small insect.', example: 'The ant is carrying food.', level: 'Elementary' },
  { id: 'e52', word: 'Ball', translation: '球', definition: 'A round object used in games.', example: 'Throw the ball to me.', level: 'Elementary' },
  { id: 'e53', word: 'Cake', translation: '蛋糕', definition: 'A sweet food made from flour and sugar.', example: 'I love chocolate cake.', level: 'Elementary' },
  { id: 'e54', word: 'Door', translation: '門', definition: 'Something you open to enter a room.', example: 'Open the door, please.', level: 'Elementary' },
  { id: 'e55', word: 'Eye', translation: '眼睛', definition: 'The part of your body you see with.', example: 'Close your eyes.', level: 'Elementary' },
  { id: 'e56', word: 'Frog', translation: '青蛙', definition: 'A small green animal that jumps.', example: 'The frog is green.', level: 'Elementary' },
  { id: 'e57', word: 'Game', translation: '遊戲', definition: 'Something you play for fun.', example: 'Do you want to play a game?', level: 'Elementary' },
  { id: 'e58', word: 'Hand', translation: '手', definition: 'The part of your body at the end of your arm.', example: 'Wash your hands.', level: 'Elementary' },
  { id: 'e59', word: 'Ink', translation: '墨水', definition: 'Colored liquid used for writing.', example: 'There is blue ink on my shirt.', level: 'Elementary' },
  { id: 'e60', word: 'Jar', translation: '罐子', definition: 'A glass container with a lid.', example: 'The jam is in the jar.', level: 'Elementary' },
  { id: 'e61', word: 'King', translation: '國王', definition: 'A male ruler of a country.', example: 'The king has a crown.', level: 'Elementary' },
  { id: 'e62', word: 'Leaf', translation: '樹葉', definition: 'The green part of a plant.', example: 'The leaf fell off the tree.', level: 'Elementary' },
  { id: 'e63', word: 'Map', translation: '地圖', definition: 'A drawing of an area.', example: 'We need a map.', level: 'Elementary' },
  { id: 'e64', word: 'Net', translation: '網子', definition: 'Something made of strings used for catching fish.', example: 'The fisherman has a net.', level: 'Elementary' },
  { id: 'e65', word: 'Oil', translation: '油', definition: 'A thick liquid used for cooking.', example: 'We need some cooking oil.', level: 'Elementary' },
  { id: 'e66', word: 'Pig', translation: '豬', definition: 'A farm animal.', example: 'The pig is eating.', level: 'Elementary' },
  { id: 'e67', word: 'Quit', translation: '停止/放棄', definition: 'To stop doing something.', example: 'Never quit your dreams.', level: 'Elementary' },
  { id: 'e68', word: 'Red', translation: '紅色', definition: 'A bright color like blood.', example: 'The apple is red.', level: 'Elementary' },
  { id: 'e69', word: 'Ship', translation: '船', definition: 'A large boat.', example: 'The ship is in the ocean.', level: 'Elementary' },
  { id: 'e70', word: 'Toy', translation: '玩具', definition: 'Something children play with.', example: 'This is my favorite toy.', level: 'Elementary' },
  { id: 'e71', word: 'Unit', translation: '單位', definition: 'A standard measure.', example: 'Meter is a unit of length.', level: 'Elementary' },
  { id: 'e72', word: 'Vest', translation: '背心', definition: 'A piece of clothing without sleeves.', example: 'He is wearing a blue vest.', level: 'Elementary' },
  { id: 'e73', word: 'Work', translation: '工作', definition: 'Physical or mental effort.', example: 'I have a lot of work to do.', level: 'Elementary' },
  { id: 'e74', word: 'X-ray', translation: 'X光', definition: 'A photograph of the inside of your body.', example: 'The doctor took an X-ray.', level: 'Elementary' },
  { id: 'e75', word: 'Year', translation: '年', definition: 'A period of 12 months.', example: 'Happy New Year!', level: 'Elementary' },
  { id: 'e76', word: 'Zip', translation: '拉鍊', definition: 'Something used to close a bag or coat.', example: 'Zip up your jacket.', level: 'Elementary' },
  { id: 'e77', word: 'Arm', translation: '手臂', definition: 'The part of your body from shoulder to hand.', example: 'He has strong arms.', level: 'Elementary' },
  { id: 'e78', word: 'Bus', translation: '巴士', definition: 'A large vehicle for many people.', example: 'The bus is late.', level: 'Elementary' },
  { id: 'e79', word: 'Cloud', translation: '雲', definition: 'A white mass in the sky.', example: 'There are many clouds today.', level: 'Elementary' },
  { id: 'e80', word: 'Desk', translation: '桌子', definition: 'A table used for working.', example: 'Put your book on the desk.', level: 'Elementary' },
  { id: 'e81', word: 'Ear', translation: '耳朵', definition: 'The part of your body you hear with.', example: 'We have two ears.', level: 'Elementary' },
  { id: 'e82', word: 'Fire', translation: '火', definition: 'Heat and light from something burning.', example: 'The fire is hot.', level: 'Elementary' },
  { id: 'e83', word: 'Gift', translation: '禮物', definition: 'Something you give to someone.', example: 'This is a gift for you.', level: 'Elementary' },
  { id: 'e84', word: 'Hat', translation: '帽子', definition: 'Something you wear on your head.', example: 'I like your hat.', level: 'Elementary' },
  { id: 'e85', word: 'Ice', translation: '冰', definition: 'Frozen water.', example: 'The ice is cold.', level: 'Elementary' },
  { id: 'e86', word: 'Job', translation: '工作', definition: 'Regular work that you do for money.', example: 'He has a new job.', level: 'Elementary' },
  { id: 'e87', word: 'Kid', translation: '小孩', definition: 'A child.', example: 'The kids are playing.', level: 'Elementary' },
  { id: 'e88', word: 'Leg', translation: '腿', definition: 'The part of your body you walk with.', example: 'He has long legs.', level: 'Elementary' },
  { id: 'e89', word: 'Man', translation: '男人', definition: 'An adult male.', example: 'That man is my father.', level: 'Elementary' },
  { id: 'e90', word: 'Nurse', translation: '護士', definition: 'Someone who takes care of sick people.', example: 'The nurse is very kind.', level: 'Elementary' },
  { id: 'e91', word: 'Open', translation: '開啟', definition: 'Not closed.', example: 'The window is open.', level: 'Elementary' },
  { id: 'e92', word: 'Park', translation: '公園', definition: 'A large public garden.', example: 'Let\'s go to the park.', level: 'Elementary' },
  { id: 'e93', word: 'Quick', translation: '快速的', definition: 'Moving fast.', example: 'Be quick!', level: 'Elementary' },
  { id: 'e94', word: 'Road', translation: '道路', definition: 'A hard surface for vehicles.', example: 'The road is long.', level: 'Elementary' },
  { id: 'e95', word: 'Sky', translation: '天空', definition: 'The area above the Earth.', example: 'The sky is blue.', level: 'Elementary' },
  { id: 'e96', word: 'Table', translation: '桌子', definition: 'A piece of furniture with a flat top.', example: 'Dinner is on the table.', level: 'Elementary' },
  { id: 'e97', word: 'Use', translation: '使用', definition: 'To do something with an object.', example: 'Can I use your phone?', level: 'Elementary' },
  { id: 'e98', word: 'Very', translation: '非常', definition: 'In a high degree.', example: 'Thank you very much.', level: 'Elementary' },
  { id: 'e99', word: 'Wall', translation: '牆壁', definition: 'The side of a room.', example: 'The wall is white.', level: 'Elementary' },
  { id: 'e100', word: 'Zoo', translation: '動物園', definition: 'A place for animals.', example: 'The zoo is big.', level: 'Elementary' },
  // ... 此處後續將補齊至 1000 字
];
