import { VocabWord } from "../vocab-data";

export const JUNIOR_VOCAB: VocabWord[] = [
  { id: 'j1', word: 'Ability', translation: '能力', definition: 'The power or skill to do something.', example: 'Success depends on your ability to work hard.', level: 'Junior' },
  { id: 'j2', word: 'Believe', translation: '相信', definition: 'To feel sure that something is true.', example: 'I believe that we can win.', level: 'Junior' },
  { id: 'j3', word: 'Common', translation: '常見的/共同的', definition: 'Happening often or existing in large numbers.', example: 'Colds are more common in winter.', level: 'Junior' },
  { id: 'j4', word: 'Degree', translation: '程度/度數', definition: 'A unit for measuring temperature.', example: 'It was 30 degrees yesterday.', level: 'Junior' },
  { id: 'j5', word: 'Effort', translation: '努力', definition: 'Physical or mental activity needed to achieve something.', example: 'He put a lot of effort into the project.', level: 'Junior' },
  { id: 'j6', word: 'Future', translation: '未來', definition: 'The time that will come after the present.', example: 'I am worried about the future.', level: 'Junior' },
  { id: 'j7', word: 'Government', translation: '政府', definition: 'The group of people who rule a country.', example: 'The government is making new laws.', level: 'Junior' },
  { id: 'j8', word: 'History', translation: '歷史', definition: 'The study of past events.', example: 'I like reading books about history.', level: 'Junior' },
  { id: 'j9', word: 'Improve', translation: '改善/進步', definition: 'To make or become better.', example: 'I want to improve my English.', level: 'Junior' },
  { id: 'j10', word: 'Knowledge', translation: '知識', definition: 'Information and understanding that you have.', example: 'His knowledge of computers is amazing.', level: 'Junior' },
  { id: 'j11', word: 'Language', translation: '語言', definition: 'A system of communication.', example: 'English is a global language.', level: 'Junior' },
  { id: 'j12', word: 'Market', translation: '市場', definition: 'A place where things are bought and sold.', example: 'I bought these vegetables at the market.', level: 'Junior' },
  { id: 'j13', word: 'Nature', translation: '大自然', definition: 'The physical world, including plants and animals.', example: 'I love being out in nature.', level: 'Junior' },
  { id: 'j14', word: 'Object', translation: '物體/目標', definition: 'A thing that you can see or touch.', example: 'There are many strange objects in the room.', level: 'Junior' },
  { id: 'j15', word: 'Patient', translation: '有耐心的', definition: 'Able to stay calm and not get angry.', example: 'You need to be patient with children.', level: 'Junior' },
  { id: 'j16', word: 'Quality', translation: '品質', definition: 'How good or bad something is.', example: 'The quality of the food is excellent.', level: 'Junior' },
  { id: 'j17', word: 'Resource', translation: '資源', definition: 'Something that can be used to help you.', example: 'The library is a great resource.', level: 'Junior' },
  { id: 'j18', word: 'Support', translation: '支持', definition: 'To help or encourage someone.', example: 'My family always supports me.', level: 'Junior' },
  { id: 'j19', word: 'Traffic', translation: '交通', definition: 'The vehicles moving on a road.', example: 'The traffic is heavy this morning.', level: 'Junior' },
  { id: 'j20', word: 'Understand', translation: '理解', definition: 'To know the meaning of something.', example: 'Do you understand the question?', level: 'Junior' },
  { id: 'j21', word: 'Vehicle', translation: '車輛', definition: 'Something used for transporting people or goods.', example: 'Cars and buses are vehicles.', level: 'Junior' },
  { id: 'j22', word: 'Weather', translation: '天氣', definition: 'The state of the atmosphere.', example: 'The weather is fine today.', level: 'Junior' },
  { id: 'j23', word: 'Young', translation: '年輕的', definition: 'Having lived for only a short time.', example: 'She is a young girl.', level: 'Junior' },
  { id: 'j24', word: 'Zero', translation: '零', definition: 'The number 0.', example: 'It is ten degrees below zero.', level: 'Junior' },
  { id: 'j25', word: 'Advice', translation: '建議', definition: 'An opinion recommended to someone.', example: 'He gave me some good advice.', level: 'Junior' },
  { id: 'j26', word: 'Balance', translation: '平衡', definition: 'A state where things are equal.', example: 'Keep your balance on the bike.', level: 'Junior' },
  { id: 'j27', word: 'Capital', translation: '首都', definition: 'The city where the government is based.', example: 'Taipei is the capital of Taiwan.', level: 'Junior' },
  { id: 'j28', word: 'Danger', translation: '危險', definition: 'The possibility of harm or death.', example: 'The sign warns of danger.', level: 'Junior' },
  { id: 'j29', word: 'Energy', translation: '能量/能源', definition: 'The power to do work.', example: 'Solar energy is clean.', level: 'Junior' },
  { id: 'j30', word: 'Factory', translation: '工廠', definition: 'A building where things are made.', example: 'My uncle works in a factory.', level: 'Junior' },
  { id: 'j31', word: 'Global', translation: '全球的', definition: 'Relating to the whole world.', example: 'Global warming is a serious issue.', level: 'Junior' },
  { id: 'j32', word: 'Healthy', translation: '健康的', definition: 'In good physical condition.', example: 'I want to live a healthy life.', level: 'Junior' },
  { id: 'j33', word: 'Imagine', translation: '想像', definition: 'To form a picture in your mind.', example: 'Can you imagine living on Mars?', level: 'Junior' },
  { id: 'j34', word: 'Journey', translation: '旅程', definition: 'An act of traveling.', example: 'It was a long journey by train.', level: 'Junior' },
  { id: 'j35', word: 'Kitchen', translation: '廚房', definition: 'A room where food is cooked.', example: 'Mom is cooking in the kitchen.', level: 'Junior' },
  { id: 'j36', word: 'Library', translation: '圖書館', definition: 'A place where books are kept.', example: 'I go to the library every Friday.', level: 'Junior' },
  { id: 'j37', word: 'Message', translation: '訊息', definition: 'A piece of information sent to someone.', example: 'I left a message for you.', level: 'Junior' },
  { id: 'j38', word: 'Notice', translation: '注意/公告', definition: 'To see or pay attention to.', example: 'Did you notice his new haircut?', level: 'Junior' },
  { id: 'j39', word: 'Opinion', translation: '意見', definition: 'A thought or belief about something.', example: 'In my opinion, this is the best book.', level: 'Junior' },
  { id: 'j40', word: 'Practice', translation: '練習', definition: 'Doing something regularly to improve.', example: 'Practice makes perfect.', level: 'Junior' },
  { id: 'j41', word: 'Reason', translation: '理由', definition: 'The cause of something.', example: 'What is the reason for your delay?', level: 'Junior' },
  { id: 'j42', word: 'Science', translation: '科學', definition: 'The study of the natural world.', example: 'I enjoy my science classes.', level: 'Junior' },
  { id: 'j43', word: 'Temperature', translation: '溫度', definition: 'How hot or cold something is.', example: 'The temperature is rising.', level: 'Junior' },
  { id: 'j44', word: 'Unique', translation: '獨特的', definition: 'Being the only one of its kind.', example: 'Each fingerprint is unique.', level: 'Junior' },
  { id: 'j45', word: 'Village', translation: '村莊', definition: 'A very small town in the country.', example: 'He lives in a small village.', level: 'Junior' },
  { id: 'j46', word: 'Warning', translation: '警告', definition: 'A piece of advice given to avoid danger.', example: 'The siren was a warning.', level: 'Junior' },
  { id: 'j47', word: 'Youth', translation: '青春/年輕人', definition: 'The period of being young.', example: 'Enjoy your youth.', level: 'Junior' },
  { id: 'j48', word: 'Area', translation: '區域', definition: 'A part of a place or town.', example: 'This is a quiet area.', level: 'Junior' },
  { id: 'j49', word: 'Benefit', translation: '好處/利益', definition: 'An advantage or profit.', example: 'Exercise has many benefits.', level: 'Junior' },
  { id: 'j50', word: 'Century', translation: '世紀', definition: 'A period of 100 years.', example: 'We are in the 21st century.', level: 'Junior' },
  { id: 'j51', word: 'Develop', translation: '發展', definition: 'To grow or change into something more advanced.', example: 'The city is developing fast.', level: 'Junior' },
  { id: 'j52', word: 'Education', translation: '教育', definition: 'The process of teaching or learning.', example: 'Education is very important.', level: 'Junior' },
  { id: 'j53', word: 'Favorite', translation: '最喜愛的', definition: 'Best liked.', example: 'Blue is my favorite color.', level: 'Junior' },
  { id: 'j54', word: 'Goal', translation: '目標', definition: 'Something you want to achieve.', example: 'My goal is to be a doctor.', level: 'Junior' },
  { id: 'j55', word: 'Honest', translation: '誠實的', definition: 'Telling the truth.', example: 'He is an honest man.', level: 'Junior' },
  { id: 'j56', word: 'Income', translation: '收入', definition: 'Money received for work.', example: 'He has a high monthly income.', level: 'Junior' },
  { id: 'j57', word: 'Junior', translation: '初級的/國中的', definition: 'Lower in rank or age.', example: 'He is a junior high student.', level: 'Junior' },
  { id: 'j58', word: 'Keyword', translation: '關鍵字', definition: 'A word used to find information.', example: 'Search for the keyword online.', level: 'Junior' },
  { id: 'j59', word: 'Level', translation: '程度/水平', definition: 'A position on a scale of amount or quality.', example: 'My English level is intermediate.', level: 'Junior' },
  { id: 'j60', word: 'Member', translation: '成員', definition: 'A person in a group.', example: 'She is a member of the club.', level: 'Junior' },
  { id: 'j61', word: 'Neighbor', translation: '鄰居', definition: 'A person living next door.', example: 'My neighbor is very friendly.', level: 'Junior' },
  { id: 'j62', word: 'Outdoor', translation: '戶外的', definition: 'Happening outside.', example: 'I like outdoor activities.', level: 'Junior' },
  { id: 'j63', word: 'Percent', translation: '百分比', definition: 'Out of every hundred.', example: 'Ten percent of the students are absent.', level: 'Junior' },
  { id: 'j64', word: 'Quarter', translation: '四分之一', definition: 'One of four equal parts.', example: 'It is a quarter past three.', level: 'Junior' },
  { id: 'j65', word: 'Recent', translation: '最近的', definition: 'Happened not long ago.', example: 'This is a recent photo.', level: 'Junior' },
  { id: 'j66', word: 'System', translation: '系統', definition: 'A set of connected things.', example: 'The solar system is huge.', level: 'Junior' },
  { id: 'j67', word: 'Target', translation: '目標', definition: 'Something you aim at.', example: 'We reached our sales target.', level: 'Junior' },
  { id: 'j68', word: 'Useful', translation: '有用的', definition: 'Helping to do something.', example: 'This is a useful tool.', level: 'Junior' },
  { id: 'j69', word: 'Value', translation: '價值', definition: 'The importance or worth of something.', example: 'The value of the house went up.', level: 'Junior' },
  { id: 'j70', word: 'Wealthy', translation: '富有', definition: 'Having a lot of money.', example: 'He is a wealthy businessman.', level: 'Junior' },
  { id: 'j71', word: 'Accept', translation: '接受', definition: 'To receive something offered.', example: 'I accept your gift.', level: 'Junior' },
  { id: 'j72', word: 'Behavior', translation: '行為', definition: 'The way someone acts.', example: 'His behavior was excellent.', level: 'Junior' },
  { id: 'j73', word: 'Collect', translation: '收集', definition: 'To bring things together.', example: 'I collect stamps.', level: 'Junior' },
  { id: 'j74', word: 'Display', translation: '展示', definition: 'To show something.', example: 'The museum displays old paintings.', level: 'Junior' },
  { id: 'j75', word: 'Energy', translation: '能量', definition: 'Power from physical sources.', example: 'Kids have a lot of energy.', level: 'Junior' },
  { id: 'j76', word: 'Famous', translation: '著名的', definition: 'Known by many people.', example: 'He is a famous singer.', level: 'Junior' },
  { id: 'j77', word: 'Gather', translation: '聚集', definition: 'To come together.', example: 'A crowd gathered around the scene.', level: 'Junior' },
  { id: 'j78', word: 'History', translation: '歷史', definition: 'Past events.', example: 'Study history to learn from mistakes.', level: 'Junior' },
  { id: 'j79', word: 'Island', translation: '島嶼', definition: 'Land surrounded by water.', example: 'Taiwan is an island.', level: 'Junior' },
  { id: 'j80', word: 'Judge', translation: '評斷/法官', definition: 'To form an opinion about someone.', example: 'Don\'t judge a book by its cover.', level: 'Junior' },
  { id: 'j81', word: 'Keep', translation: '保持/留下', definition: 'To continue to have.', example: 'Keep the change.', level: 'Junior' },
  { id: 'j82', word: 'Local', translation: '當地的', definition: 'In the area where you live.', example: 'Buy fresh local food.', level: 'Junior' },
  { id: 'j83', word: 'Memory', translation: '記憶', definition: 'The ability to remember.', example: 'She has a good memory.', level: 'Junior' },
  { id: 'j84', word: 'Normal', translation: '正常的', definition: 'Usual or expected.', example: 'It is normal to feel nervous.', level: 'Junior' },
  { id: 'j85', word: 'Observe', translation: '觀察', definition: 'To watch carefully.', example: 'Observe the stars at night.', level: 'Junior' },
  { id: 'j86', word: 'Perfect', translation: '完美的', definition: 'Without any flaws.', example: 'The weather is perfect.', level: 'Junior' },
  { id: 'j87', word: 'Quality', translation: '品質', definition: 'Standard of excellence.', example: 'Good quality lasts longer.', level: 'Junior' },
  { id: 'j88', word: 'Relieve', translation: '減輕/緩解', definition: 'To make pain or stress less.', example: 'This medicine will relieve your pain.', level: 'Junior' },
  { id: 'j89', word: 'Safety', translation: '安全', definition: 'Protection from danger.', example: 'Safety first.', level: 'Junior' },
  { id: 'j90', word: 'Trust', translation: '信任', definition: 'To believe someone is honest.', example: 'I trust you.', level: 'Junior' },
  { id: 'j91', word: 'Update', translation: '更新', definition: 'To make more modern.', example: 'I need to update my computer.', level: 'Junior' },
  { id: 'j92', word: 'Various', translation: '多樣的', definition: 'Many different types.', example: 'Various flowers are in bloom.', level: 'Junior' },
  { id: 'j93', word: 'Waste', translation: '浪費/垃圾', definition: 'Using more than needed.', example: 'Don\'t waste water.', level: 'Junior' },
  { id: 'j94', word: 'Youth', translation: '青少年/活力', definition: 'Young people.', example: 'The youth are our future.', level: 'Junior' },
  { id: 'j95', word: 'Active', translation: '積極的', definition: 'Taking part in many activities.', example: 'He is an active member.', level: 'Junior' },
  { id: 'j96', word: 'Breath', translation: '呼吸', definition: 'Air taken into the lungs.', example: 'Take a deep breath.', level: 'Junior' },
  { id: 'j97', word: 'Current', translation: '目前的', definition: 'Happening now.', example: 'The current situation is difficult.', level: 'Junior' },
  { id: 'j98', word: 'Decision', translation: '決定', definition: 'A choice made after thinking.', example: 'It was a tough decision.', level: 'Junior' },
  { id: 'j99', word: 'Excite', translation: '使興奮', definition: 'To make someone feel happy and eager.', example: 'The news excited everyone.', level: 'Junior' },
  { id: 'j100', word: 'Flow', translation: '流動', definition: 'To move steadily like water.', example: 'The river flows into the sea.', level: 'Junior' },
  // ... 此處後續將補齊至 1000 字
];
];
