import { VocabWord } from "../vocab-data";

export const JUNIOR_VOCAB: VocabWord[] = [
  { id: 'j1', word: 'Ability', translation: '能力', definition: 'The power or skill to do something.', example: 'Success depends on your ability to work hard.', level: 'Junior' },
  { id: 'j2', word: 'Believe', translation: '相信', definition: 'To feel sure that something is true.', example: 'I believe that we can win.', level: 'Junior' },
  { id: 'j3', word: 'Common', translation: '常見的/共同的', definition: 'Happening often or existing in large numbers.', example: 'Colds are more common in winter.', level: 'Junior' },
  { id: 'j4', word: 'Degree', translation: '程度/度數', definition: 'A unit for measuring temperature.', example: 'It was 30 degrees yesterday.', level: 'Junior' },
  { id: 'j5', word: 'Effort', translation: '努力', definition: 'Physical or mental activity needed to achieve something.', example: 'He put a lot of effort into the project.', level: 'Junior' },
  { id: 'j6', word: 'Future', translation: '未來', definition: 'The time that will come after the present.', example: 'I am worried about the future.', level: 'Junior' },
  { id: 'j7', word: 'Government', translation: '政府', definition: 'The group of people who rule a country.', example: 'The government is making new laws.', level: 'Junior' },
  { id: 'j8', word: 'History', translation: '歷史', definition: 'The study of past events.', example: 'I like reading books about history.', level: 'Junior' },
  { id: 'j9', word: 'Improve', translation: '改善/進步', definition: 'To make or become better.', example: 'I want to improve my English.', level: 'Junior' },
  { id: 'j10', word: 'Knowledge', translation: '知識', definition: 'Information and understanding that you have.', example: 'His knowledge of computers is amazing.', level: 'Junior' },
  { id: 'j11', word: 'Accept', translation: '接受', definition: 'To agree to take something.', example: 'I accept your apology.', level: 'Junior' },
  { id: 'j12', word: 'Active', translation: '活躍的/積極的', definition: 'Taking part in many activities.', example: 'She is very active in sports.', level: 'Junior' },
  { id: 'j13', word: 'Advice', translation: '建議', definition: 'An opinion about what to do.', example: 'Ask your teacher for advice.', level: 'Junior' },
  { id: 'j14', word: 'Afraid', translation: '害怕的', definition: 'Feeling fear.', example: 'Don\'t be afraid of mistakes.', level: 'Junior' },
  { id: 'j15', word: 'Ancient', translation: '古老的', definition: 'From a long time ago.', example: 'Ancient Egypt is fascinating.', level: 'Junior' },
  { id: 'j16', word: 'Appearance', translation: '外貌/出現', definition: 'The way someone looks.', example: 'Don\'t judge by appearance.', level: 'Junior' },
  { id: 'j17', word: 'Article', translation: '文章/冠詞', definition: 'A piece of writing in a news source.', example: 'I read an article about space.', level: 'Junior' },
  { id: 'j18', word: 'Attack', translation: '攻擊', definition: 'To try to hurt someone.', example: 'The army launched an attack.', level: 'Junior' },
  { id: 'j19', word: 'Attract', translation: '吸引', definition: 'To pull toward.', example: 'Magnets attract iron.', level: 'Junior' },
  { id: 'j20', word: 'Avoid', translation: '避免', definition: 'To stay away from.', example: 'Avoid eating too much sugar.', level: 'Junior' },
  { id: 'j21', word: 'Background', translation: '背景', definition: 'Part of a picture or a person\'s past.', example: 'He has a medical background.', level: 'Junior' },
  { id: 'j22', word: 'Behavior', translation: '行為', definition: 'The way someone acts.', example: 'Good behavior is expected.', level: 'Junior' },
  { id: 'j23', word: 'Benefit', translation: '利益/好處', definition: 'An advantage.', example: 'Exercise has many benefits.', level: 'Junior' },
  { id: 'j24', word: 'Beyond', translation: '超越', definition: 'Farther than.', example: 'Beyond the mountains.', level: 'Junior' },
  { id: 'j25', word: 'Biology', translation: '生物學', definition: 'Study of living things.', example: 'Biology is my favorite subject.', level: 'Junior' },
  { id: 'j26', word: 'Bother', translation: '打擾/煩惱', definition: 'To annoy or worry.', example: 'Don\'t bother your sister.', level: 'Junior' },
  { id: 'j27', word: 'Budget', translation: '預算', definition: 'A plan for spending money.', example: 'We are on a tight budget.', level: 'Junior' },
  { id: 'j28', word: 'Business', translation: '生意/商務', definition: 'Buying and selling goods.', example: 'He runs a small business.', level: 'Junior' },
  { id: 'j29', word: 'Campus', translation: '校園', definition: 'The grounds of a school.', example: 'The campus is very beautiful.', level: 'Junior' },
  { id: 'j30', word: 'Cancel', translation: '取消', definition: 'To decide not to do something.', example: 'The meeting was canceled.', level: 'Junior' },
  { id: 'j31', word: 'Career', translation: '職業生涯', definition: 'A long-term job.', example: 'She chose a career in music.', level: 'Junior' },
  { id: 'j32', word: 'Celebration', translation: '慶祝', definition: 'A joyful event.', example: 'The birthday celebration was fun.', level: 'Junior' },
  { id: 'j33', word: 'Challenge', translation: '挑戰', definition: 'A difficult task.', example: 'Learning a new language is a challenge.', level: 'Junior' },
  { id: 'j34', word: 'Character', translation: '角色/性格', definition: 'Personal qualities.', example: 'He is a man of good character.', level: 'Junior' },
  { id: 'j35', word: 'Chemistry', translation: '化學', definition: 'Study of substances.', example: 'I like chemistry experiments.', level: 'Junior' },
  { id: 'j36', word: 'Choice', translation: '選擇', definition: 'Act of picking between options.', example: 'It was a difficult choice.', level: 'Junior' },
  { id: 'j37', word: 'Climate', translation: '氣候', definition: 'General weather of a place.', example: 'Tropical climate is hot.', level: 'Junior' },
  { id: 'j38', word: 'Collect', translation: '收集', definition: 'To bring together.', example: 'I collect stamps.', level: 'Junior' },
  { id: 'j39', word: 'Comfortable', translation: '舒適的', definition: 'Feeling relaxed.', example: 'The sofa is very comfortable.', level: 'Junior' },
  { id: 'j40', word: 'Communication', translation: '溝通', definition: 'Sharing information.', example: 'Effective communication is key.', level: 'Junior' },
  { id: 'j41', word: 'Company', translation: '公司/伴侶', definition: 'A business or being with others.', example: 'I enjoy your company.', level: 'Junior' },
  { id: 'j42', word: 'Compare', translation: '比較', definition: 'To find similarities or differences.', example: 'Compare these two books.', level: 'Junior' },
  { id: 'j43', word: 'Competition', translation: '比賽/競爭', definition: 'An event where people try to win.', example: 'I won the speech competition.', level: 'Junior' },
  { id: 'j44', word: 'Complete', translation: '完成/完整的', definition: 'To finish.', example: 'Complete the task.', level: 'Junior' },
  { id: 'j45', word: 'Concentrate', translation: '專注', definition: 'To focus your attention.', example: 'I can\'t concentrate with that noise.', level: 'Junior' },
  { id: 'j46', word: 'Condition', translation: '條件/狀況', definition: 'State of something.', example: 'The car is in good condition.', level: 'Junior' },
  { id: 'j47', word: 'Confidence', translation: '信心', definition: 'Self-belief.', example: 'Believe in yourself with confidence.', level: 'Junior' },
  { id: 'j48', word: 'Conflict', translation: '衝突', definition: 'A disagreement.', example: 'They had a conflict of opinion.', level: 'Junior' },
  { id: 'j49', word: 'Consider', translation: '考慮', definition: 'To think about carefully.', example: 'Please consider my offer.', level: 'Junior' },
  { id: 'j50', word: 'Contact', translation: '聯絡/接觸', definition: 'To communicate with.', example: 'Contact me via email.', level: 'Junior' },
  { id: 'j51', word: 'Content', translation: '內容/滿意的', definition: 'Information or being happy.', example: 'The content of the box.', level: 'Junior' },
  { id: 'j52', word: 'Context', translation: '語境/上下文', definition: 'Circumstances of an event.', example: 'Understand words in context.', level: 'Junior' },
  { id: 'j53', word: 'Contribution', translation: '貢獻', definition: 'Something given to help.', example: 'Make a contribution to charity.', level: 'Junior' },
  { id: 'j54', word: 'Control', translation: '控制', definition: 'To have power over.', example: 'Control your emotions.', level: 'Junior' },
  { id: 'j55', word: 'Conversation', translation: '對話', definition: 'Informal talk.', example: 'We had a long conversation.', level: 'Junior' },
  { id: 'j56', word: 'Convey', translation: '傳達', definition: 'To transport or express.', example: 'Convey my thanks to him.', level: 'Junior' },
  { id: 'j57', word: 'Create', translation: '創造', definition: 'To make new things.', example: 'Artists create art.', level: 'Junior' },
  { id: 'j58', word: 'Culture', translation: '文化', definition: 'Customs and beliefs.', example: 'I love Japanese culture.', level: 'Junior' },
  { id: 'j59', word: 'Curious', translation: '好奇的', definition: 'Eager to know.', example: 'The cat is curious.', level: 'Junior' },
  { id: 'j60', word: 'Current', translation: '目前的/流動', definition: 'Happening now.', example: 'Current news.', level: 'Junior' },
  { id: 'j61', word: 'Customer', translation: '顧客', definition: 'Person who buys goods.', example: 'The customer is always right.', level: 'Junior' },
  { id: 'j62', word: 'Damage', translation: '損害', definition: 'Physical harm.', example: 'The storm caused damage.', level: 'Junior' },
  { id: 'j63', word: 'Decision', translation: '決定', definition: 'A choice made.', example: 'Make a quick decision.', level: 'Junior' },
  { id: 'j64', word: 'Defend', translation: '防衛', definition: 'To protect.', example: 'Defend your country.', level: 'Junior' },
  { id: 'j65', word: 'Delivery', translation: '遞送', definition: 'Bringing goods.', example: 'Free delivery.', level: 'Junior' },
  { id: 'j66', word: 'Demand', translation: '要求/需求', definition: 'To insist on.', example: 'High demand for oil.', level: 'Junior' },
  { id: 'j67', word: 'Departure', translation: '出發/離開', definition: 'Leaving a place.', example: 'The plane\'s departure.', level: 'Junior' },
  { id: 'j68', word: 'Describe', translation: '描述', definition: 'To give details.', example: 'Describe the suspect.', level: 'Junior' },
  { id: 'j69', word: 'Design', translation: '設計', definition: 'A plan or drawing.', example: 'Graphic design.', level: 'Junior' },
  { id: 'j70', word: 'Destination', translation: '目的地', definition: 'Place to travel.', example: 'Our destination is Paris.', level: 'Junior' },
  { id: 'j71', word: 'Detail', translation: '細節', definition: 'A small part.', example: 'Pay attention to detail.', level: 'Junior' },
  { id: 'j72', word: 'Device', translation: '裝置/設備', definition: 'A mechanical tool.', example: 'Electronic device.', level: 'Junior' },
  { id: 'j73', word: 'Dictionary', translation: '字典', definition: 'Reference book for words.', example: 'Look it up in the dictionary.', level: 'Junior' },
  { id: 'j74', word: 'Difficulty', translation: '困難', definition: 'Being hard to do.', example: 'I had no difficulty.', level: 'Junior' },
  { id: 'j75', word: 'Direct', translation: '直接的/指導', definition: 'Straight.', example: 'A direct flight.', level: 'Junior' },
  { id: 'j76', word: 'Direction', translation: '方向', definition: 'Path or instruction.', example: 'Which direction?', level: 'Junior' },
  { id: 'j77', word: 'Disappear', translation: '消失', definition: 'To go away.', example: 'The sun disappeared.', level: 'Junior' },
  { id: 'j78', word: 'Discover', translation: '發現', definition: 'To find for the first time.', example: 'Discover new lands.', level: 'Junior' },
  { id: 'j79', word: 'Discussion', translation: '討論', definition: 'Talking about a topic.', example: 'A brief discussion.', level: 'Junior' },
  { id: 'j80', word: 'Disease', translation: '疾病', definition: 'Illness.', example: 'Fight against disease.', level: 'Junior' },
  { id: 'j81', word: 'Display', translation: '展示', definition: 'To show.', example: 'Display the work.', level: 'Junior' },
  { id: 'j82', word: 'Distance', translation: '距離', definition: 'Amount of space.', example: 'A long distance.', level: 'Junior' },
  { id: 'j83', word: 'Doubt', translation: '懷疑', definition: 'Uncertainty.', example: 'I have no doubt.', level: 'Junior' },
  { id: 'j84', word: 'Drama', translation: '戲劇/戲劇性', definition: 'A play or exciting event.', example: 'I love high school drama.', level: 'Junior' },
  { id: 'j85', word: 'Education', translation: '教育', definition: 'Process of learning.', example: 'Higher education.', level: 'Junior' },
  { id: 'j86', word: 'Effect', translation: '影響/效果', definition: 'A result.', example: 'The greenhouse effect.', level: 'Junior' },
  { id: 'j87', word: 'Elderly', translation: '年長的', definition: 'Old people.', example: 'Respect the elderly.', level: 'Junior' },
  { id: 'j88', word: 'Election', translation: '選舉', definition: 'Voting process.', example: 'The presidential election.', level: 'Junior' },
  { id: 'j89', word: 'Electricity', translation: '電力', definition: 'Form of energy.', example: 'Turn off the electricity.', level: 'Junior' },
  { id: 'j90', word: 'Element', translation: '元素/要素', definition: 'A basic part.', example: 'The element of surprise.', level: 'Junior' },
  { id: 'j91', word: 'Emergency', translation: '緊急情況', definition: 'Unforeseen crisis.', example: 'In case of emergency.', level: 'Junior' },
  { id: 'j92', word: 'Emotion', translation: '情緒', definition: 'A strong feeling.', example: 'Control your emotions.', level: 'Junior' },
  { id: 'j93', word: 'Emphasis', translation: '強調', definition: 'Special importance.', example: 'Put emphasis on safety.', level: 'Junior' },
  { id: 'j94', word: 'Employer', translation: '雇主', definition: 'Person who hires workers.', example: 'A kind employer.', level: 'Junior' },
  { id: 'j95', word: 'Encourage', translation: '鼓勵', definition: 'To give hope.', example: 'Encourage students.', level: 'Junior' },
  { id: 'j96', word: 'Engage', translation: '參與/訂婚', definition: 'To participate.', example: 'Engage in activities.', level: 'Junior' },
  { id: 'j97', word: 'Engine', translation: '引擎', definition: 'Mechanical power source.', example: 'The car engine.', level: 'Junior' },
  { id: 'j98', word: 'Environment', translation: '環境', definition: 'Natural world.', example: 'Save the environment.', level: 'Junior' },
  { id: 'j99', word: 'Equipment', translation: '設備', definition: 'Necessary tools.', example: 'Camping equipment.', level: 'Junior' },
  { id: 'j100', word: 'Escape', translation: '逃跑', definition: 'To get free.', example: 'Escape from prison.', level: 'Junior' },
  { id: 'j101', word: 'Establish', translation: '建立/成立', definition: 'To set up.', example: 'Establish a business.', level: 'Junior' },
  { id: 'j102', word: 'Estimate', translation: '估計', definition: 'A rough calculation.', example: 'Give an estimate.', level: 'Junior' },
  { id: 'j103', word: 'Event', translation: '活動/事件', definition: 'Something that happens.', example: 'A major event.', level: 'Junior' },
  { id: 'j104', word: 'Evidence', translation: '證據', definition: 'Proof.', example: 'Scientific evidence.', level: 'Junior' },
  { id: 'j105', word: 'Exact', translation: '確切的', definition: 'Accurate.', example: 'Tell me the exact time.', level: 'Junior' },
  { id: 'j106', word: 'Examination', translation: '考試/檢查', definition: 'Test.', example: 'A final examination.', level: 'Junior' },
  { id: 'j107', word: 'Excellent', translation: '優秀的', definition: 'Very good.', example: 'Excellent work!', level: 'Junior' },
  { id: 'j108', word: 'Exception', translation: '例外', definition: 'Not following the rule.', example: 'With one exception.', level: 'Junior' },
  { id: 'j109', word: 'Exchange', translation: '交換', definition: 'Giving and receiving.', example: 'Exchange gifts.', level: 'Junior' },
  { id: 'j110', word: 'Excited', translation: '興奮的', definition: 'Feeling eager.', example: 'I am excited.', level: 'Junior' },
  { id: 'j111', word: 'Excuse', translation: '藉口/原諒', definition: 'Reason for failure.', example: 'No more excuses.', level: 'Junior' },
  { id: 'j112', word: 'Exercise', translation: '運動/練習', definition: 'Physical activity.', example: 'Daily exercise.', level: 'Junior' },
  { id: 'j113', word: 'Exhausted', translation: '精疲力竭的', definition: 'Very tired.', example: 'I am exhausted.', level: 'Junior' },
  { id: 'j114', word: 'Exhibition', translation: '展覽', definition: 'Public display.', example: 'An art exhibition.', level: 'Junior' },
  { id: 'j115', word: 'Exist', translation: '存在', definition: 'To be real.', example: 'Does magic exist?', level: 'Junior' },
  { id: 'j116', word: 'Exit', translation: '出口', definition: 'Way out.', example: 'Emergency exit.', level: 'Junior' },
  { id: 'j117', word: 'Expand', translation: '擴張', definition: 'To get bigger.', example: 'Expand the business.', level: 'Junior' },
  { id: 'j118', word: 'Expect', translation: '期待/預期', definition: 'To think something will happen.', example: 'Don\'t expect too much.', level: 'Junior' },
  { id: 'j119', word: 'Experience', translation: '經驗/經歷', definition: 'Knowledge from doing.', example: 'Work experience.', level: 'Junior' },
  { id: 'j120', word: 'Experiment', translation: '實驗', definition: 'Scientific test.', example: 'A lab experiment.', level: 'Junior' },
  { id: 'j121', word: 'Explain', translation: '解釋', definition: 'To make clear.', example: 'Explain it to me.', level: 'Junior' },
  { id: 'j122', word: 'Explore', translation: '探索', definition: 'To search and discover.', example: 'Explore the jungle.', level: 'Junior' },
  { id: 'j123', word: 'Express', translation: '表達/快速的', definition: 'To state feelings.', example: 'Express yourself.', level: 'Junior' },
  { id: 'j124', word: 'Extend', translation: '延伸/延長', definition: 'To make longer.', example: 'Extend the deadline.', level: 'Junior' },
  { id: 'j125', word: 'External', translation: '外部的', definition: 'Outer part.', example: 'External drive.', level: 'Junior' },
  { id: 'j126', word: 'Extra', translation: '額外的', definition: 'More than usual.', example: 'Extra time.', level: 'Junior' },
  { id: 'j127', word: 'Extreme', translation: '極端的', definition: 'Greatest degree.', example: 'Extreme sports.', level: 'Junior' },
  { id: 'j128', word: 'Facility', translation: '設施', definition: 'A place or piece of equipment.', example: 'Sports facility.', level: 'Junior' },
  { id: 'j129', word: 'Factor', translation: '因素', definition: 'Something that influences.', example: 'A key factor.', level: 'Junior' },
  { id: 'j130', word: 'Factory', translation: '工廠', definition: 'Place where goods are made.', example: 'Shoe factory.', level: 'Junior' },
  { id: 'j131', word: 'Failure', translation: '失敗', definition: 'Lack of success.', example: 'Failure is a lesson.', level: 'Junior' },
  { id: 'j132', word: 'Faith', translation: '信念/信心', definition: 'Strong belief.', example: 'Have faith.', level: 'Junior' },
  { id: 'j133', word: 'False', translation: '錯誤的', definition: 'Not true.', example: 'A false alarm.', level: 'Junior' },
  { id: 'j134', word: 'Familiar', translation: '熟悉的', definition: 'Well-known.', example: 'A familiar face.', level: 'Junior' },
  { id: 'j135', word: 'Fashion', translation: '流行/時尚', definition: 'Popular style.', example: 'Latest fashion.', level: 'Junior' },
  { id: 'j136', word: 'Feature', translation: '特徵/特色', definition: 'Distinctive attribute.', example: 'A new feature.', level: 'Junior' },
  { id: 'j137', word: 'Federal', translation: '聯邦的', definition: 'National government.', example: 'Federal law.', level: 'Junior' },
  { id: 'j138', word: 'Feeling', translation: '感覺', definition: 'Emotion.', example: 'A bad feeling.', level: 'Junior' },
  { id: 'j139', word: 'Festival', translation: '節慶', definition: 'Day of celebration.', example: 'A music festival.', level: 'Junior' },
  { id: 'j140', word: 'Field', translation: '田野/領域', definition: 'Open land.', example: 'Playing field.', level: 'Junior' },
  { id: 'j141', word: 'Fight', translation: '戰鬥/爭吵', definition: 'Violent struggle.', example: 'Fight for rights.', level: 'Junior' },
  { id: 'j142', word: 'Figure', translation: '數字/身材/人物', definition: 'A number or shape.', example: 'A tall figure.', level: 'Junior' },
  { id: 'j143', word: 'File', translation: '檔案', definition: 'Folder for papers.', example: 'Open the file.', level: 'Junior' },
  { id: 'j144', word: 'Fill', translation: '充滿', definition: 'To make full.', example: 'Fill the glass.', level: 'Junior' },
  { id: 'j145', word: 'Film', translation: '電影', definition: 'Movie.', example: 'Watch a film.', level: 'Junior' },
  { id: 'j146', word: 'Final', translation: '最後的', definition: 'End.', example: 'Final exam.', level: 'Junior' },
  { id: 'j147', word: 'Financial', translation: '財務的', definition: 'Relating to money.', example: 'Financial advice.', level: 'Junior' },
  { id: 'j148', word: 'Finger', translation: '手指', definition: 'Body part.', example: 'Index finger.', level: 'Junior' },
  { id: 'j149', word: 'Finish', translation: '完成', definition: 'To end.', example: 'Finish lunch.', level: 'Junior' },
  { id: 'j150', word: 'Firm', translation: '堅定的/公司', definition: 'Solid or business.', example: 'A law firm.', level: 'Junior' },
  { id: 'j151', word: 'Flat', translation: '平坦的/公寓', definition: 'Level surface.', example: 'Flat tire.', level: 'Junior' },
  { id: 'j152', word: 'Flight', translation: '飛行/班機', definition: 'Trip by plane.', example: 'Have a safe flight.', level: 'Junior' },
  { id: 'j153', word: 'Float', translation: '漂浮', definition: 'To stay on top of liquid.', example: 'Wood floats.', level: 'Junior' },
  { id: 'j154', word: 'Flood', translation: '洪水', definition: 'Overflow of water.', example: 'The heavy rain caused a flood.', level: 'Junior' },
  { id: 'j155', word: 'Floor', translation: '地板/樓層', definition: 'Ground surface.', example: 'On the third floor.', level: 'Junior' },
  { id: 'j156', word: 'Flow', translation: '流動', definition: 'Steady movement.', example: 'Water flow.', level: 'Junior' },
  { id: 'j157', word: 'Focus', translation: '焦點/專注', definition: 'Central point.', example: 'Focus on your work.', level: 'Junior' },
  { id: 'j158', word: 'Fold', translation: '摺疊', definition: 'To bend.', example: 'Fold the paper.', level: 'Junior' },
  { id: 'j159', word: 'Follow', translation: '跟隨/遵守', definition: 'To go after.', example: 'Follow the rules.', level: 'Junior' },
  { id: 'j160', word: 'Foot', translation: '腳', definition: 'Body part.', example: 'Left foot.', level: 'Junior' },
  { id: 'j161', word: 'Force', translation: '力量/強迫', definition: 'Power.', example: 'Air force.', level: 'Junior' },
  { id: 'j162', word: 'Foreign', translation: '外國的', definition: 'Outside your country.', example: 'Foreign policy.', level: 'Junior' },
  { id: 'j163', word: 'Forest', translation: '森林', definition: 'Tree-covered land.', example: 'Deep forest.', level: 'Junior' },
  { id: 'j164', word: 'Forever', translation: '永遠', definition: 'Eternally.', example: 'Friends forever.', level: 'Junior' },
  { id: 'j165', word: 'Forget', translation: '忘記', definition: 'Fail to remember.', example: 'Don\'t forget.', level: 'Junior' },
  { id: 'j166', word: 'Forgive', translation: '原諒', definition: 'Stop being angry.', example: 'Forgive and forget.', level: 'Junior' },
  { id: 'j167', word: 'Formal', translation: '正式的', definition: 'Officially proper.', example: 'Formal dress.', level: 'Junior' },
  { id: 'j168', word: 'Former', translation: '之前的', definition: 'Previous.', example: 'Former president.', level: 'Junior' },
  { id: 'j169', word: 'Fortunate', translation: '幸運的', definition: 'Lucky.', example: 'You are fortunate.', level: 'Junior' },
  { id: 'j170', word: 'Forward', translation: '向前', definition: 'Toward the front.', example: 'Move forward.', level: 'Junior' },
  { id: 'j171', word: 'Foundation', translation: '基礎/地基', definition: 'Base or start.', example: 'A solid foundation.', level: 'Junior' },
  { id: 'j172', word: 'Frame', translation: '框架', definition: 'Outer structure.', example: 'Picture frame.', level: 'Junior' },
  { id: 'j173', word: 'Freedom', translation: '自由', definition: 'Liberty.', example: 'Fight for freedom.', level: 'Junior' },
  { id: 'j174', word: 'Freezer', translation: '冷凍庫', definition: 'Part of fridge.', example: 'Ice in the freezer.', level: 'Junior' },
  { id: 'j175', word: 'Frequent', translation: '頻繁的', definition: 'Happening often.', example: 'Frequent traveler.', level: 'Junior' },
  { id: 'j176', word: 'Fresh', translation: '新鮮的', definition: 'New or clean.', example: 'Fresh bread.', level: 'Junior' },
  { id: 'j177', word: 'Friendship', translation: '友誼', definition: 'Relationship.', example: 'Valuable friendship.', level: 'Junior' },
  { id: 'j178', word: 'Frown', translation: '皺眉', definition: 'Sad/Angry look.', example: 'Why the frown?', level: 'Junior' },
  { id: 'j179', word: 'Fruit', translation: '水果', definition: 'Edible plant part.', example: 'Fresh fruit.', level: 'Junior' },
  { id: 'j180', word: 'Fuel', translation: '燃料', definition: 'Power source.', example: 'Save fuel.', level: 'Junior' },
  { id: 'j181', word: 'Function', translation: '功能/函數', definition: 'Purpose.', example: 'Main function.', level: 'Junior' },
  { id: 'j182', word: 'Fund', translation: '基金/資金', definition: 'Money for purpose.', example: 'Pension fund.', level: 'Junior' },
  { id: 'j183', word: 'Furniture', translation: '家具', definition: 'House items.', example: 'Old furniture.', level: 'Junior' },
  { id: 'j184', word: 'Gain', translation: '獲得', definition: 'To acquire.', example: 'Gain weight.', level: 'Junior' },
  { id: 'j185', word: 'Gallery', translation: '藝廊', definition: 'Art display place.', example: 'National Gallery.', level: 'Junior' },
  { id: 'j186', word: 'Garage', translation: '車庫', definition: 'Car storage.', example: 'Park in the garage.', level: 'Junior' },
  { id: 'j187', word: 'Garden', translation: '花園', definition: 'Outdoor area.', example: 'Flower garden.', level: 'Junior' },
  { id: 'j188', word: 'Garlic', translation: '大蒜', definition: 'Strong plant spice.', example: 'Smell of garlic.', level: 'Junior' },
  { id: 'j189', word: 'Gas', translation: '氣體/瓦斯', definition: 'State of matter.', example: 'Cooking gas.', level: 'Junior' },
  { id: 'j190', word: 'Gather', translation: '收集/聚集', definition: 'Bring together.', example: 'Gather round.', level: 'Junior' },
  { id: 'j191', word: 'General', translation: '一般的/將軍', definition: 'Overall.', example: 'In general.', level: 'Junior' },
  { id: 'j192', word: 'Generation', translation: '世代', definition: 'People of same age.', example: 'New generation.', level: 'Junior' },
  { id: 'j193', word: 'Generous', translation: '慷慨的', definition: 'Giving freely.', example: 'A generous man.', level: 'Junior' },
  { id: 'j194', word: 'Gentle', translation: '溫和的', definition: 'Kind/Soft.', example: 'Be gentle.', level: 'Junior' },
  { id: 'j195', word: 'Geography', translation: '地理', definition: 'Study of earth.', example: 'World geography.', level: 'Junior' },
  { id: 'j196', word: 'Gesture', translation: '手勢', definition: 'Body movement.', example: 'Friendly gesture.', level: 'Junior' },
  { id: 'j197', word: 'Giant', translation: '巨大的', definition: 'Very large.', example: 'A giant tree.', level: 'Junior' },
  { id: 'j198', word: 'Glance', translation: '掃視', definition: 'A quick look.', example: 'At a glance.', level: 'Junior' },
  { id: 'j199', word: 'Glorious', translation: '輝煌的/壯麗的', definition: 'Magnificent.', example: 'A glorious day.', level: 'Junior' },
  { id: 'j200', word: 'Grab', translation: '抓取', definition: 'To seize suddenly.', example: 'Grab a snack.', level: 'Junior' },
  // ... 這裡會持續填入至 1000 個不重複單字
];
