import { VocabWord } from "../vocab-data";

export const SENIOR_VOCAB: VocabWord[] = [
  { id: 's1', word: 'Abundant', translation: '豐富的', definition: 'Existing in large quantities; more than enough.', example: 'The island has an abundant supply of fresh water.', level: 'Senior' },
  { id: 's2', word: 'Benchmark', translation: '基準/標竿', definition: 'A standard against which other things can be compared.', example: 'This product is the benchmark for quality.', level: 'Senior' },
  { id: 's3', word: 'Collaborate', translation: '合作', definition: 'To work with someone else for a special purpose.', example: 'The two companies agreed to collaborate on the project.', level: 'Senior' },
  { id: 's4', word: 'Dynamic', translation: '有活力的/動態的', definition: 'Full of energy or new ideas.', example: 'She is a dynamic and successful business woman.', level: 'Senior' },
  { id: 's5', word: 'Entrepreneur', translation: '企業家', definition: 'Someone who starts their own business.', example: 'He is a successful tech entrepreneur.', level: 'Senior' },
  { id: 's6', word: 'Fluctuation', translation: '波動/起伏', definition: 'A change, especially a continuous one.', example: 'The fluctuation in oil prices is worrying.', level: 'Senior' },
  { id: 's7', word: 'Genuine', translation: '真實的/誠懇的', definition: 'Real and exactly what it appears to be.', example: 'She showed genuine concern for my health.', level: 'Senior' },
  { id: 's8', word: 'Hypothesis', translation: '假設', definition: 'An idea or explanation that is not yet proven.', example: 'Scientists are testing the new hypothesis.', level: 'Senior' },
  { id: 's9', word: 'Implement', translation: '實施/執行', definition: 'To start using a plan or system.', example: 'The government promised to implement the new law.', level: 'Senior' },
  { id: 's10', word: 'Justify', translation: '證明...正當', definition: 'To give a good reason for something.', example: 'How can you justify the high cost of this car?', level: 'Senior' },
  { id: 's11', word: 'Kinetic', translation: '動能的/運動的', definition: 'Relating to or resulting from motion.', example: 'The kinetic energy of the ball is increasing.', level: 'Senior' },
  { id: 's12', word: 'Lucrative', translation: '獲利豐厚的', definition: 'Producing a lot of money.', example: 'The merger proved to be a lucrative deal.', level: 'Senior' },
  { id: 's13', word: 'Manifest', translation: '顯示/明瞭的', definition: 'Clear or obvious to the eye or mind.', example: 'Their happiness was manifest in their smiles.', level: 'Senior' },
  { id: 's14', word: 'Negotiate', translation: '談判/協商', definition: 'To try to reach an agreement.', example: 'We need to negotiate a new contract.', level: 'Senior' },
  { id: 's15', word: 'Optimistic', translation: '樂觀的', definition: 'Hopeful and confident about the future.', example: 'She is optimistic about her chances of winning.', level: 'Senior' },
  { id: 's16', word: 'Pragmatic', translation: '務實的', definition: 'Dealing with things sensibly and realistically.', example: 'We need a pragmatic approach to the problem.', level: 'Senior' },
  { id: 's17', word: 'Quantitative', translation: '定量的', definition: 'Relating to, measuring, or measured by the quantity.', example: 'Quantitative analysis is necessary for the report.', level: 'Senior' },
  { id: 's18', word: 'Resilient', translation: '有韌性的/復原力強的', definition: 'Able to withstand or recover quickly from difficult conditions.', example: 'Children are often surprisingly resilient.', level: 'Senior' },
  { id: 's19', word: 'Sustainable', translation: '永續的', definition: 'Able to be maintained at a certain rate or level.', example: 'Sustainable development is crucial for our planet.', level: 'Senior' },
  { id: 's20', word: 'Transparent', translation: '透明的/公開的', definition: 'Allowing light to pass through; easy to perceive or detect.', example: 'The glass is transparent.', level: 'Senior' },
  { id: 's21', word: 'Ultimate', translation: '最終的/極致的', definition: 'Being or happening at the end of a process.', example: 'Our ultimate goal is to win the championship.', level: 'Senior' },
  { id: 's22', word: 'Versatile', translation: '多才多藝的/多功能的', definition: 'Able to adapt or be adapted to many different functions.', example: 'He is a very versatile actor.', level: 'Senior' },
  { id: 's23', word: 'Widespread', translation: '廣泛的', definition: 'Found or distributed over a large area or number of people.', example: 'The problem is widespread in the community.', level: 'Senior' },
  { id: 's24', word: 'Yield', translation: '產量/屈服', definition: 'To produce or provide; to give way to arguments.', example: 'The harvest yielded a record crop.', level: 'Senior' },
  { id: 's25', word: 'Zealous', translation: '熱心的/狂熱的', definition: 'Showing great energy or enthusiasm.', example: 'He is a zealous supporter of the movement.', level: 'Senior' },
  { id: 's26', word: 'Ambiguous', translation: '含糊不清的', definition: 'Having more than one possible meaning.', example: 'The instructions were quite ambiguous.', level: 'Senior' },
  { id: 's27', word: 'Benevolent', translation: '仁慈的', definition: 'Well meaning and kindly.', example: 'A benevolent uncle paid for her tuition.', level: 'Senior' },
  { id: 's28', word: 'Cohesive', translation: '有凝聚力的', definition: 'Forming a united whole.', example: 'The group was not very cohesive.', level: 'Senior' },
  { id: 's29', word: 'Deteriorate', translation: '惡化', definition: 'Become progressively worse.', example: 'The weather condition began to deteriorate.', level: 'Senior' },
  { id: 's30', word: 'Eloquent', translation: '雄辯的/口才好的', definition: 'Fluent or persuasive in speaking or writing.', example: 'His speech was very eloquent.', level: 'Senior' },
  { id: 's31', word: 'Formidable', translation: '令人敬畏的', definition: 'Inspiring fear or respect through being large or powerful.', example: 'They faced a formidable opponent.', level: 'Senior' },
  { id: 's32', word: 'Gratuitous', translation: '無理由的/免費的', definition: 'Done without good reason; uncalled for.', example: 'The movie was filled with gratuitous violence.', level: 'Senior' },
  { id: 's33', word: 'Incentive', translation: '激勵/誘因', definition: 'Something that motivates or encourages someone.', example: 'Tax incentives help small businesses grow.', level: 'Senior' },
  { id: 's34', word: 'Judicious', translation: '明智的/審慎的', definition: 'Done with good judgment or sense.', example: 'We should make a judicious choice.', level: 'Senior' },
  { id: 's35', word: 'Kindle', translation: '點燃/啟發', definition: 'To set fire to; to inspire.', example: 'His words kindled our imagination.', level: 'Senior' },
  { id: 's36', word: 'Lament', translation: '哀悼/遺憾', definition: 'A passionate expression of grief or sorrow.', example: 'She lamented the loss of her friend.', level: 'Senior' },
  { id: 's37', word: 'Meticulous', translation: '一絲不苟的', definition: 'Showing great attention to detail; very careful.', example: 'He is meticulous in his work.', level: 'Senior' },
  { id: 's38', word: 'Nostalgic', translation: '懷舊的', definition: 'Feeling pleasure and sadness at the same time about the past.', example: 'Hearing the song made her feel nostalgic.', level: 'Senior' },
  { id: 's39', word: 'Obsolete', translation: '過時的/淘汰的', definition: 'No longer produced or used.', example: 'The old machines are now obsolete.', level: 'Senior' },
  { id: 's40', word: 'Pervasive', translation: '遍布的/普遍的', definition: 'Spreading widely throughout an area or a group of people.', example: 'Corruption is pervasive in the organization.', level: 'Senior' },
  { id: 's41', word: 'Quota', translation: '配額/限額', definition: 'A limited quantity of a particular product.', example: 'The country has a quota on imported cars.', level: 'Senior' },
  { id: 's42', word: 'Rational', translation: '理性的', definition: 'Based on or in accordance with reason or logic.', example: 'Let\'s make a rational decision.', level: 'Senior' },
  { id: 's43', word: 'Scrutinize', translation: '詳細檢查', definition: 'Examine or inspect closely and thoroughly.', example: 'Customers were asked to scrutinize the contract.', level: 'Senior' },
  { id: 's44', word: 'Tangible', translation: '有形的/具體的', definition: 'Perceptible by touch.', example: 'We need tangible evidence.', level: 'Senior' },
  { id: 's45', word: 'Unanimous', translation: '全體一致的', definition: 'Fully in agreement.', example: 'The decision was unanimous.', level: 'Senior' },
  { id: 's46', word: 'Vindicate', translation: '證明...無辜/維護', definition: 'Clear someone of blame or suspicion.', example: 'New evidence vindicated the suspect.', level: 'Senior' },
  { id: 's47', word: 'Withhold', translation: '保留/抑制', definition: 'Refuse to give (something that is due to or is desired by another).', example: 'The bank can withhold your payment.', level: 'Senior' },
  { id: 's48', word: 'Xenophobia', translation: '仇外心理', definition: 'Dislike of or prejudice against people from other countries.', example: 'Xenophobia is a serious social issue.', level: 'Senior' },
  { id: 's49', word: 'Yearn', translation: '渴望', definition: 'Have an intense feeling of longing for something.', example: 'They yearn for peace in the region.', level: 'Senior' },
  { id: 's50', word: 'Zenith', translation: '鼎盛/頂點', definition: 'The time at which something is most powerful or successful.', example: 'The empire reached its zenith in the 18th century.', level: 'Senior' },
  { id: 's51', word: 'Adversity', translation: '逆境/不幸', definition: 'A difficult or unpleasant situation.', example: 'He overcame many adversities.', level: 'Senior' },
  { id: 's52', word: 'Bolster', translation: '支持/加強', definition: 'To support or strengthen.', example: 'They need to bolster their defenses.', level: 'Senior' },
  { id: 's53', word: 'Conspicuous', translation: '顯眼的/明顯的', definition: 'Standing out so as to be clearly visible.', example: 'The bird has conspicuous red feathers.', level: 'Senior' },
  { id: 's54', word: 'Discreet', translation: '謹慎的', definition: 'Careful and circumspect in one\'s speech or actions.', example: 'We made discreet inquiries about him.', level: 'Senior' },
  { id: 's55', word: 'Exacerbate', translation: '惡化/加重', definition: 'Make (a problem, bad situation, or negative feeling) worse.', example: 'The recession exacerbated the unemployment problem.', level: 'Senior' },
  { id: 's56', word: 'Frugal', translation: '節儉的', definition: 'Simple and plain and costing little.', example: 'He leads a frugal life.', level: 'Senior' },
  { id: 's57', word: 'Generic', translation: '通用的', definition: 'Characteristic of or relating to a class or group of things.', example: 'Chutney is a generic term for Indian sauces.', level: 'Senior' },
  { id: 's58', word: 'Heirloom', translation: '傳家寶', definition: 'A valuable object that has belonged to a family for several generations.', example: 'This ring is a family heirloom.', level: 'Senior' },
  { id: 's59', word: 'Inevitable', translation: '不可避免的', definition: 'Certain to happen; unavoidable.', example: 'Change is inevitable.', level: 'Senior' },
  { id: 's60', word: 'Juxtapose', translation: '並列', definition: 'Place or deal with close together for contrasting effect.', example: 'The exhibition juxtaposes modern and ancient art.', level: 'Senior' },
  { id: 's61', word: 'Knowledgeable', translation: '知識淵博的', definition: 'Intelligent and well informed.', example: 'She is very knowledgeable about law.', level: 'Senior' },
  { id: 's62', word: 'Lenient', translation: '寬大的/仁慈的', definition: 'Of a punishment or person in authority permissive, merciful, or tolerant.', example: 'The judge was lenient with him.', level: 'Senior' },
  { id: 's63', word: 'Magnanimous', translation: '寬大的/慷慨的', definition: 'Generous or forgiving, especially toward a rival or less powerful person.', example: 'She was magnanimous in victory.', level: 'Senior' },
  { id: 's64', word: 'Negligible', translation: '可忽略的', definition: 'So small or unimportant as to be not worth considering.', example: 'The cost was negligible.', level: 'Senior' },
  { id: 's65', word: 'Ostentatious', translation: '炫耀的', definition: 'Characterized by vulgar or pretentious display.', example: 'The room was decorated in an ostentatious style.', level: 'Senior' },
  { id: 's66', word: 'Plausible', translation: '有道理的/貌似真實的', definition: 'Seeming reasonable or probable.', example: 'That is a plausible explanation.', level: 'Senior' },
  { id: 's67', word: 'Qualitative', translation: '定性的', definition: 'Relating to, measuring, or measured by the quality of something.', example: 'Qualitative research is very important.', level: 'Senior' },
  { id: 's68', word: 'Reconcile', translation: '和解/調和', definition: 'Restore friendly relations between.', example: 'They were finally reconciled.', level: 'Senior' },
  { id: 's69', word: 'Spontaneous', translation: '自發的', definition: 'Performed or occurring as a result of a sudden inner impulse.', example: 'The audience broke into spontaneous applause.', level: 'Senior' },
  { id: 's70', word: 'Tenacious', translation: '頑強的/固執的', definition: 'Tending to keep a firm hold of something; clinging or adhering closely.', example: 'He is a tenacious negotiator.', level: 'Senior' },
  { id: 's71', word: 'Ubiquitous', translation: '無處不在的', definition: 'Present, appearing, or found everywhere.', example: 'Mobile phones are ubiquitous nowadays.', level: 'Senior' },
  { id: 's72', word: 'Vulnerable', translation: '脆弱的/易受傷的', definition: 'Susceptible to physical or emotional attack or harm.', example: 'We were in a vulnerable position.', level: 'Senior' },
  { id: 's73', word: 'Wary', translation: '謹慎的/提防的', definition: 'Feeling or showing caution about possible dangers or problems.', example: 'He was wary of strangers.', level: 'Senior' },
  { id: 's74', word: 'Xylography', translation: '木刻術', definition: 'The art of engraving on wood.', example: 'Xylography is an ancient printing technique.', level: 'Senior' },
  { id: 's75', word: 'Yielding', translation: '順從的/易彎曲的', definition: 'Complying with the requests or desires of others.', example: 'He is a yielding person.', level: 'Senior' },
  { id: 's76', word: 'Zealot', translation: '狂熱者', definition: 'A person who is fanatical and uncompromising in pursuit of their ideals.', example: 'He is a religious zealot.', level: 'Senior' },
  { id: 's77', word: 'Astute', translation: '精明的', definition: 'Having or showing an ability to accurately assess situations or people.', example: 'She is an astute businesswoman.', level: 'Senior' },
  { id: 's78', word: 'Belligerent', translation: '好鬥的', definition: 'Hostile and aggressive.', example: 'A belligerent tone in his voice.', level: 'Senior' },
  { id: 's79', word: 'Complacent', translation: '自滿的', definition: 'Showing smug or uncritical satisfaction with oneself or one\'s achievements.', example: 'Don\'t become complacent about your success.', level: 'Senior' },
  { id: 's80', word: 'Dogmatic', translation: '教條的/武斷的', definition: 'Inclined to lay down principles as undeniably true.', example: 'His dogmatic approach to the subject was annoying.', level: 'Senior' },
  { id: 's81', word: 'Exemplary', translation: '典範的/榜樣的', definition: 'Serving as a desirable model; representing the best of its kind.', example: 'His behavior was exemplary.', level: 'Senior' },
  { id: 's82', word: 'Fastidious', translation: '挑剔的', definition: 'Very attentive to and concerned about accuracy and detail.', example: 'He is fastidious about his clothes.', level: 'Senior' },
  { id: 's83', word: 'Gregarious', translation: '愛社交的', definition: 'Fond of company; sociable.', example: 'He is a gregarious person.', level: 'Senior' },
  { id: 's84', word: 'Hierarchy', definition: '階層/等級制度', translation: 'A system in which members of an organization are ranked.', example: 'The corporate hierarchy is complex.', level: 'Senior' },
  { id: 's85', word: 'Impeccable', translation: '無暇的', definition: 'In accordance with the highest standards; faultless.', example: 'She has impeccable manners.', level: 'Senior' },
  { id: 's86', word: 'Jovial', translation: '愉快的', definition: 'Cheerful and friendly.', example: 'He is in a jovial mood.', level: 'Senior' },
  { id: 's87', word: 'Labyrinth', translation: '迷宮', definition: 'A complicated irregular network of passages or paths.', example: 'The city was a labyrinth of narrow streets.', level: 'Senior' },
  { id: 's88', word: 'Malignant', translation: '惡性的', definition: 'Malevolent; tending to produce death.', example: 'The tumor was found to be malignant.', level: 'Senior' },
  { id: 's89', word: 'Nuance', translation: '細微差別', definition: 'A subtle difference in or shade of meaning, expression, or sound.', example: 'The painter used nuances of color.', level: 'Senior' },
  { id: 's90', word: 'Ominous', translation: '不祥的', definition: 'Giving the impression that something bad is going to happen.', example: 'The ominous dark clouds suggested a storm.', level: 'Senior' },
  { id: 's91', word: 'Paramount', translation: '至上的/最重要的', definition: 'More important than anything else.', example: 'Safety is of paramount importance.', level: 'Senior' },
  { id: 's92', word: 'Quaint', translation: '古雅的', definition: 'Attractively unusual or old-fashioned.', example: 'A quaint little cottage.', level: 'Senior' },
  { id: 's93', word: 'Redundant', translation: '多餘的/累贅的', definition: 'Not or no longer needed or useful.', example: 'His comments were redundant.', level: 'Senior' },
  { id: 's94', word: 'Succinct', translation: '簡潔的', definition: 'Briefly and clearly expressed.', example: 'A succinct summary of the report.', level: 'Senior' },
  { id: 's95', word: 'Transient', translation: '短暫的', definition: 'Lasting only for a short time; impermanent.', example: 'A transient population.', level: 'Senior' },
  { id: 's96', word: 'Ubiquity', translation: '無處不在', definition: 'The state of being everywhere.', example: 'The ubiquity of the internet.', level: 'Senior' },
  { id: 's97', word: 'Vacillate', translation: '猶豫不決', definition: 'Alternate or waver between different opinions or actions.', example: 'He vacillated between the two choices.', level: 'Senior' },
  { id: 's98', word: 'Whimsical', translation: '古怪的/異想天開的', definition: 'Playfully quaint or fanciful.', example: 'A whimsical sense of humor.', level: 'Senior' },
  { id: 's99', word: 'Yield', translation: '產量/屈服', definition: 'Amount produced.', example: 'The annual yield was high.', level: 'Senior' },
  { id: 's100', word: 'Zeal', translation: '熱忱', definition: 'Great energy or enthusiasm.', example: 'He worked with great zeal.', level: 'Senior' },
];
