import { VocabWord } from "../vocab-data";

export const SENIOR_VOCAB: VocabWord[] = [
  { id: 's1', word: 'Abundant', translation: '豐富的', definition: 'Existing in large quantities; more than enough.', example: 'The island has an abundant supply of fresh water.', level: 'Senior' },
  { id: 's2', word: 'Benchmark', translation: '基準/標竿', definition: 'A standard against which other things can be compared.', example: 'This product is the benchmark for quality.', level: 'Senior' },
  { id: 's3', word: 'Collaborate', translation: '合作', definition: 'To work with someone else for a special purpose.', example: 'The two companies agreed to collaborate on the project.', level: 'Senior' },
  { id: 's4', word: 'Dynamic', translation: '有活力的/動態的', definition: 'Full of energy or new ideas.', example: 'She is a dynamic and successful business woman.', level: 'Senior' },
  { id: 's5', word: 'Entrepreneur', translation: '企業家', definition: 'Someone who starts their own business.', example: 'He is a successful tech entrepreneur.', level: 'Senior' },
  { id: 's6', word: 'Fluctuation', translation: '波動/起伏', definition: 'A change, especially a continuous one.', example: 'The fluctuation in oil prices is worrying.', level: 'Senior' },
  { id: 's7', word: 'Genuine', translation: '真實的/誠懇的', definition: 'Real and exactly what it appears to be.', example: 'She showed genuine concern for my health.', level: 'Senior' },
  { id: 's8', word: 'Hypothesis', translation: '假設', definition: 'An idea or explanation that is not yet proven.', example: 'Scientists are testing the new hypothesis.', level: 'Senior' },
  { id: 's9', word: 'Implement', translation: '實施/執行', definition: 'To start using a plan or system.', example: 'The government promised to implement the new law.', level: 'Senior' },
  { id: 's10', word: 'Justify', translation: '證明...正當', definition: 'To give a good reason for something.', example: 'How can you justify the high cost of this car?', level: 'Senior' },
  { id: 's11', word: 'Kinetic', translation: '動能的/運動的', definition: 'Relating to or resulting from motion.', example: 'The kinetic energy of the ball is increasing.', level: 'Senior' },
  { id: 's12', word: 'Lucrative', translation: '獲利豐厚的', definition: 'Producing a lot of money.', example: 'The merger proved to be a lucrative deal.', level: 'Senior' },
  { id: 's13', word: 'Manifest', translation: '顯示/明瞭的', definition: 'Clear or obvious to the eye or mind.', example: 'Their happiness was manifest in their smiles.', level: 'Senior' },
  { id: 's14', word: 'Negotiate', translation: '談判/協商', definition: 'To try to reach an agreement.', example: 'We need to negotiate a new contract.', level: 'Senior' },
  { id: 's15', word: 'Optimistic', translation: '樂觀的', definition: 'Hopeful and confident about the future.', example: 'She is optimistic about her chances of winning.', level: 'Senior' },
  { id: 's16', word: 'Pragmatic', translation: '務實的', definition: 'Dealing with things sensibly and realistically.', example: 'We need a pragmatic approach to the problem.', level: 'Senior' },
  { id: 's17', word: 'Quantitative', translation: '定量的', definition: 'Relating to, measuring, or measured by the quantity.', example: 'Quantitative analysis is necessary for the report.', level: 'Senior' },
  { id: 's18', word: 'Resilient', translation: '有韌性的/復原力強的', definition: 'Able to withstand or recover quickly from difficult conditions.', example: 'Children are often surprisingly resilient.', level: 'Senior' },
  { id: 's19', word: 'Sustainable', translation: '永續的', definition: 'Able to be maintained at a certain rate or level.', example: 'Sustainable development is crucial for our planet.', level: 'Senior' },
  { id: 's20', word: 'Transparent', translation: '透明的/公開的', definition: 'Allowing light to pass through; easy to perceive or detect.', example: 'The glass is transparent.', level: 'Senior' },
  { id: 's21', word: 'Ultimate', translation: '最終的/極致的', definition: 'Being or happening at the end of a process.', example: 'Our ultimate goal is to win the championship.', level: 'Senior' },
  { id: 's22', word: 'Versatile', translation: '多才多藝的/多功能的', definition: 'Able to adapt or be adapted to many different functions.', example: 'He is a very versatile actor.', level: 'Senior' },
  { id: 's23', word: 'Widespread', translation: '廣泛的', definition: 'Found or distributed over a large area or number of people.', example: 'The problem is widespread in the community.', level: 'Senior' },
  { id: 's24', word: 'Yield', translation: '產量/屈服', definition: 'To produce or provide; to give way to arguments.', example: 'The harvest yielded a record crop.', level: 'Senior' },
  { id: 's25', word: 'Zealous', translation: '熱心的/狂熱的', definition: 'Showing great energy or enthusiasm.', example: 'He is a zealous supporter of the movement.', level: 'Senior' },
  { id: 's26', word: 'Ambiguous', translation: '含糊不清的', definition: 'Having more than one possible meaning.', example: 'The instructions were quite ambiguous.', level: 'Senior' },
  { id: 's27', word: 'Benevolent', translation: '仁慈的', definition: 'Well meaning and kindly.', example: 'A benevolent uncle paid for her tuition.', level: 'Senior' },
  { id: 's28', word: 'Cohesive', translation: '有凝聚力的', definition: 'Forming a united whole.', example: 'The group was not very cohesive.', level: 'Senior' },
  { id: 's29', word: 'Deteriorate', translation: '惡化', definition: 'Become progressively worse.', example: 'The weather condition began to deteriorate.', level: 'Senior' },
  { id: 's30', word: 'Eloquent', translation: '雄辯的/口才好的', definition: 'Fluent or persuasive in speaking or writing.', example: 'His speech was very eloquent.', level: 'Senior' },
  { id: 's31', word: 'Formidable', translation: '令人敬畏的', definition: 'Inspiring fear or respect through being large or powerful.', example: 'They faced a formidable opponent.', level: 'Senior' },
  { id: 's32', word: 'Gratuitous', translation: '無理由的/免費的', definition: 'Done without good reason; uncalled for.', example: 'The movie was filled with gratuitous violence.', level: 'Senior' },
  { id: 's33', word: 'Incentive', translation: '激勵/誘因', definition: 'Something that motivates or encourages someone.', example: 'Tax incentives help small businesses grow.', level: 'Senior' },
  { id: 's34', word: 'Judicious', translation: '明智的/審慎的', definition: 'Done with good judgment or sense.', example: 'We should make a judicious choice.', level: 'Senior' },
  { id: 's35', word: 'Kindle', translation: '點燃/啟發', definition: 'To set fire to; to inspire.', example: 'His words kindled our imagination.', level: 'Senior' },
  { id: 's36', word: 'Lament', translation: '哀悼/遺憾', definition: 'A passionate expression of grief or sorrow.', example: 'She lamented the loss of her friend.', level: 'Senior' },
  { id: 's37', word: 'Meticulous', translation: '一絲不苟的', definition: 'Showing great attention to detail; very careful.', example: 'He is meticulous in his work.', level: 'Senior' },
  { id: 's38', word: 'Nostalgic', translation: '懷舊的', definition: 'Feeling pleasure and sadness at the same time about the past.', example: 'Hearing the song made her feel nostalgic.', level: 'Senior' },
  { id: 's39', word: 'Obsolete', translation: '過時的/淘汰的', definition: 'No longer produced or used.', example: 'The old machines are now obsolete.', level: 'Senior' },
  { id: 's40', word: 'Pervasive', translation: '遍布的/普遍的', definition: 'Spreading widely throughout an area or a group of people.', example: 'Corruption is pervasive in the organization.', level: 'Senior' },
  { id: 's41', word: 'Quota', translation: '配額/限額', definition: 'A limited quantity of a particular product.', example: 'The country has a quota on imported cars.', level: 'Senior' },
  { id: 's42', word: 'Rational', translation: '理性的', definition: 'Based on or in accordance with reason or logic.', example: 'Let\'s make a rational decision.', level: 'Senior' },
  { id: 's43', word: 'Scrutinize', translation: '詳細檢查', definition: 'Examine or inspect closely and thoroughly.', example: 'Customers were asked to scrutinize the contract.', level: 'Senior' },
  { id: 's44', word: 'Tangible', translation: '有形的/具體的', definition: 'Perceptible by touch.', example: 'We need tangible evidence.', level: 'Senior' },
  { id: 's45', word: 'Unanimous', translation: '全體一致的', definition: 'Fully in agreement.', example: 'The decision was unanimous.', level: 'Senior' },
  { id: 's46', word: 'Vindicate', translation: '證明...無辜/維護', definition: 'Clear someone of blame or suspicion.', example: 'New evidence vindicated the suspect.', level: 'Senior' },
  { id: 's47', word: 'Withhold', translation: '保留/抑制', definition: 'Refuse to give (something that is due to or is desired by another).', example: 'The bank can withhold your payment.', level: 'Senior' },
  { id: 's48', word: 'Xenophobia', translation: '仇外心理', definition: 'Dislike of or prejudice against people from other countries.', example: 'Xenophobia is a serious social issue.', level: 'Senior' },
  { id: 's49', word: 'Yearn', translation: '渴望', definition: 'Have an intense feeling of longing for something.', example: 'They yearn for peace in the region.', level: 'Senior' },
  { id: 's50', word: 'Zenith', translation: '鼎盛/頂點', definition: 'The time at which something is most powerful or successful.', example: 'The empire reached its zenith in the 18th century.', level: 'Senior' },
  { id: 's51', word: 'Adversity', translation: '逆境/不幸', definition: 'A difficult or unpleasant situation.', example: 'He overcame many adversities.', level: 'Senior' },
  { id: 's52', word: 'Bolster', translation: '支持/加強', definition: 'To support or strengthen.', example: 'They need to bolster their defenses.', level: 'Senior' },
  { id: 's53', word: 'Conspicuous', translation: '顯眼的/明顯的', definition: 'Standing out so as to be clearly visible.', example: 'The bird has conspicuous red feathers.', level: 'Senior' },
  { id: 's54', word: 'Discreet', translation: '謹慎的', definition: 'Careful and circumspect in one\'s speech or actions.', example: 'We made discreet inquiries about him.', level: 'Senior' },
  { id: 's55', word: 'Exacerbate', translation: '惡化/加重', definition: 'Make (a problem, bad situation, or negative feeling) worse.', example: 'The recession exacerbated the unemployment problem.', level: 'Senior' },
  { id: 's56', word: 'Frugal', translation: '節儉的', definition: 'Simple and plain and costing little.', example: 'He leads a frugal life.', level: 'Senior' },
  { id: 's57', word: 'Generic', translation: '通用的', definition: 'Characteristic of or relating to a class or group of things.', example: 'Chutney is a generic term for Indian sauces.', level: 'Senior' },
  { id: 's58', word: 'Heirloom', translation: '傳家寶', definition: 'A valuable object that has belonged to a family for several generations.', example: 'This ring is a family heirloom.', level: 'Senior' },
  { id: 's59', word: 'Inevitable', translation: '不可避免的', definition: 'Certain to happen; unavoidable.', example: 'Change is inevitable.', level: 'Senior' },
  { id: 's60', word: 'Juxtapose', translation: '並列', definition: 'Place or deal with close together for contrasting effect.', example: 'The exhibition juxtaposes modern and ancient art.', level: 'Senior' },
  { id: 's61', word: 'Knowledgeable', translation: '知識淵博的', definition: 'Intelligent and well informed.', example: 'She is very knowledgeable about law.', level: 'Senior' },
  { id: 's62', word: 'Lenient', translation: '寬大的/仁慈的', definition: 'Of a punishment or person in authority permissive, merciful, or tolerant.', example: 'The judge was lenient with him.', level: 'Senior' },
  { id: 's63', word: 'Magnanimous', translation: '寬大的/慷慨的', definition: 'Generous or forgiving, especially toward a rival or less powerful person.', example: 'She was magnanimous in victory.', level: 'Senior' },
  { id: 's64', word: 'Negligible', translation: '可忽略的', definition: 'So small or unimportant as to be not worth considering.', example: 'The cost was negligible.', level: 'Senior' },
  { id: 's65', word: 'Ostentatious', translation: '炫耀的', definition: 'Characterized by vulgar or pretentious display.', example: 'The room was decorated in an ostentatious style.', level: 'Senior' },
  { id: 's66', word: 'Plausible', translation: '有道理的/貌似真實的', definition: 'Seeming reasonable or probable.', example: 'That is a plausible explanation.', level: 'Senior' },
  { id: 's67', word: 'Qualitative', translation: '定性的', definition: 'Relating to, measuring, or measured by the quality of something.', example: 'Qualitative research is very important.', level: 'Senior' },
  { id: 's68', word: 'Reconcile', translation: '和解/調和', definition: 'Restore friendly relations between.', example: 'They were finally reconciled.', level: 'Senior' },
  { id: 's69', word: 'Spontaneous', translation: '自發的', definition: 'Performed or occurring as a result of a sudden inner impulse.', example: 'The audience broke into spontaneous applause.', level: 'Senior' },
  { id: 's70', word: 'Tenacious', translation: '頑強的/固執的', definition: 'Tending to keep a firm hold of something; clinging or adhering closely.', example: 'He is a tenacious negotiator.', level: 'Senior' },
  { id: 's71', word: 'Ubiquitous', translation: '無處不在的', definition: 'Present, appearing, or found everywhere.', example: 'Mobile phones are ubiquitous nowadays.', level: 'Senior' },
  { id: 's72', word: 'Vulnerable', translation: '脆弱的/易受傷的', definition: 'Susceptible to physical or emotional attack or harm.', example: 'We were in a vulnerable position.', level: 'Senior' },
  { id: 's73', word: 'Wary', translation: '謹慎的/提防的', definition: 'Feeling or showing caution about possible dangers or problems.', example: 'He was wary of strangers.', level: 'Senior' },
  { id: 's74', word: 'Xylography', translation: '木刻術', definition: 'The art of engraving on wood.', example: 'Xylography is an ancient printing technique.', level: 'Senior' },
  { id: 's75', word: 'Yielding', translation: '順從的/易彎曲的', definition: 'Complying with the requests or desires of others.', example: 'He is a yielding person.', level: 'Senior' },
  { id: 's76', word: 'Zealot', translation: '狂熱者', definition: 'A person who is fanatical and uncompromising in pursuit of their ideals.', example: 'He is a religious zealot.', level: 'Senior' },
  { id: 's77', word: 'Astute', translation: '精明的', definition: 'Having or showing an ability to accurately assess situations or people.', example: 'She is an astute businesswoman.', level: 'Senior' },
  { id: 's78', word: 'Belligerent', translation: '好鬥的', definition: 'Hostile and aggressive.', example: 'A belligerent tone in his voice.', level: 'Senior' },
  { id: 's79', word: 'Complacent', translation: '自滿的', definition: 'Showing smug or uncritical satisfaction with oneself or one\'s achievements.', example: 'Don\'t become complacent about your success.', level: 'Senior' },
  { id: 's80', word: 'Dogmatic', translation: '教條的/武斷的', definition: 'Inclined to lay down principles as undeniably true.', example: 'His dogmatic approach to the subject was annoying.', level: 'Senior' },
  { id: 's81', word: 'Exemplary', translation: '典範的/榜樣的', definition: 'Serving as a desirable model; representing the best of its kind.', example: 'His behavior was exemplary.', level: 'Senior' },
  { id: 's82', word: 'Fastidious', translation: '挑剔的', definition: 'Very attentive to and concerned about accuracy and detail.', example: 'He is fastidious about his clothes.', level: 'Senior' },
  { id: 's83', word: 'Gregarious', translation: '愛社交的', definition: 'Fond of company; sociable.', example: 'He is a gregarious person.', level: 'Senior' },
  { id: 's84', word: 'Hierarchy', definition: '階層/等級制度', translation: 'A system in which members of an organization are ranked.', example: 'The corporate hierarchy is complex.', level: 'Senior' },
  { id: 's85', word: 'Impeccable', translation: '無暇的', definition: 'In accordance with the highest standards; faultless.', example: 'She has impeccable manners.', level: 'Senior' },
  { id: 's86', word: 'Jovial', translation: '愉快的', definition: 'Cheerful and friendly.', example: 'He is in a jovial mood.', level: 'Senior' },
  { id: 's87', word: 'Labyrinth', translation: '迷宮', definition: 'A complicated irregular network of passages or paths.', example: 'The city was a labyrinth of narrow streets.', level: 'Senior' },
  { id: 's88', word: 'Malignant', translation: '惡性的', definition: 'Malevolent; tending to produce death.', example: 'The tumor was found to be malignant.', level: 'Senior' },
  { id: 's89', word: 'Nuance', translation: '細微差別', definition: 'A subtle difference in or shade of meaning, expression, or sound.', example: 'The painter used nuances of color.', level: 'Senior' },
  { id: 's90', word: 'Ominous', translation: '不祥的', definition: 'Giving the impression that something bad is going to happen.', example: 'The ominous dark clouds suggested a storm.', level: 'Senior' },
  { id: 's91', word: 'Paramount', translation: '至上的/最重要的', definition: 'More important than anything else.', example: 'Safety is of paramount importance.', level: 'Senior' },
  { id: 's92', word: 'Quaint', translation: '古雅的', definition: 'Attractively unusual or old-fashioned.', example: 'A quaint little cottage.', level: 'Senior' },
  { id: 's93', word: 'Redundant', translation: '多餘的/累贅的', definition: 'Not or no longer needed or useful.', example: 'His comments were redundant.', level: 'Senior' },
  { id: 's94', word: 'Succinct', translation: '簡潔的', definition: 'Briefly and clearly expressed.', example: 'A succinct summary of the report.', level: 'Senior' },
  { id: 's95', word: 'Transient', translation: '短暫的', definition: 'Lasting only for a short time; impermanent.', example: 'A transient population.', level: 'Senior' },
  { id: 's96', word: 'Ubiquity', translation: '無處不在', definition: 'The state of being everywhere.', example: 'The ubiquity of the internet.', level: 'Senior' },
  { id: 's97', word: 'Vacillate', translation: '猶豫不決', definition: 'Alternate or waver between different opinions or actions.', example: 'He vacillated between the two choices.', level: 'Senior' },
  { id: 's98', word: 'Whimsical', translation: '古怪的/異想天開的', definition: 'Playfully quaint or fanciful.', example: 'A whimsical sense of humor.', level: 'Senior' },
  { id: 's99', word: 'Yield', translation: '產量/屈服', definition: 'Amount produced.', example: 'The annual yield was high.', level: 'Senior' },
  { id: 's100', word: 'Zeal', translation: '熱忱', definition: 'Great energy or enthusiasm.', example: 'He worked with great zeal.', level: 'Senior' },
  { id: 's101', word: 'Abstract', translation: '抽象的', definition: 'Existing in thought or as an idea.', example: 'An abstract concept.', level: 'Senior' },
  { id: 's102', word: 'Academic', translation: '學術的', definition: 'Relating to education and scholarship.', example: 'Academic excellence.', level: 'Senior' },
  { id: 's103', word: 'Accelerate', translation: '加速', definition: 'To increase speed.', example: 'Accelerate the process.', level: 'Senior' },
  { id: 's104', word: 'Accessible', translation: '易接近的', definition: 'Easy to approach or reach.', example: 'Accessible information.', level: 'Senior' },
  { id: 's105', word: 'Accumulate', translation: '累積', definition: 'To gather or collect.', example: 'Accumulate wealth.', level: 'Senior' },
  { id: 's106', word: 'Accuracy', translation: '準確性', definition: 'The state of being correct.', example: 'Check for accuracy.', level: 'Senior' },
  { id: 's107', word: 'Acknowledge', translation: '承認', definition: 'To accept the truth of.', example: 'Acknowledge the facts.', level: 'Senior' },
  { id: 's108', word: 'Acquisition', translation: '取得/收購', definition: 'The act of getting something.', example: 'Language acquisition.', level: 'Senior' },
  { id: 's109', word: 'Adaptation', translation: '適應', definition: 'Process of changing to suit conditions.', example: 'Evolutionary adaptation.', level: 'Senior' },
  { id: 's110', word: 'Adequate', translation: '足夠的', definition: 'Satisfactory or acceptable.', example: 'Adequate resources.', level: 'Senior' },
  { id: 's111', word: 'Adhere', translation: '堅持/遵守', definition: 'To stick to a surface or rule.', example: 'Adhere to guidelines.', level: 'Senior' },
  { id: 's112', word: 'Advocacy', translation: '擁護/主張', definition: 'Public support for a cause.', example: 'Health advocacy.', level: 'Senior' },
  { id: 's113', word: 'Aesthetic', translation: '美學的', definition: 'Relating to beauty.', example: 'Aesthetic appeal.', level: 'Senior' },
  { id: 's114', word: 'Affiliate', translation: '附屬', definition: 'To connect with an organization.', example: 'Affiliate company.', level: 'Senior' },
  { id: 's115', word: 'Aggregation', translation: '聚合', definition: 'The formation of a group.', example: 'Data aggregation.', level: 'Senior' },
  { id: 's116', word: 'Allocate', translation: '分配', definition: 'To distribute resources.', example: 'Allocate funds.', level: 'Senior' },
  { id: 's117', word: 'Alteration', translation: '改變', definition: 'A change or modification.', example: 'Major alteration.', level: 'Senior' },
  { id: 's118', word: 'Ambivalence', translation: '矛盾心理', definition: 'State of having mixed feelings.', example: 'Feel ambivalence.', level: 'Senior' },
  { id: 's119', word: 'Amplify', translation: '放大/增強', definition: 'To increase intensity.', example: 'Amplify the signal.', level: 'Senior' },
  { id: 's120', word: 'Analogy', translation: '類比', definition: 'A comparison between things.', example: 'A clear analogy.', level: 'Senior' },
  { id: 's121', word: 'Annotate', translation: '註解', definition: 'To add explanatory notes.', example: 'Annotate the text.', level: 'Senior' },
  { id: 's122', word: 'Anomaly', translation: '異常', definition: 'Something that deviates from normal.', example: 'A genetic anomaly.', level: 'Senior' },
  { id: 's123', word: 'Anticipate', translation: '預期', definition: 'To look forward to.', example: 'Anticipate problems.', level: 'Senior' },
  { id: 's124', word: 'Apathy', translation: '冷漠', definition: 'Lack of interest or concern.', example: 'Political apathy.', level: 'Senior' },
  { id: 's125', word: 'Apparatus', translation: '設備/裝置', definition: 'Technical equipment.', example: 'Lab apparatus.', level: 'Senior' },
  { id: 's126', word: 'Appendix', translation: '附錄', definition: 'Supplementary material at end of book.', example: 'See Appendix A.', level: 'Senior' },
  { id: 's127', word: 'Appraisal', translation: '評估', definition: 'An act of assessing something.', example: 'Performance appraisal.', level: 'Senior' },
  { id: 's128', word: 'Arbitrary', translation: '武斷的', definition: 'Based on random choice.', example: 'Arbitrary decision.', level: 'Senior' },
  { id: 's129', word: 'Archetype', translation: '原型', definition: 'A very typical example.', example: 'Hero archetype.', level: 'Senior' },
  { id: 's130', word: 'Architecture', translation: '建築/架構', definition: 'Design of buildings/systems.', example: 'System architecture.', level: 'Senior' },
  { id: 's131', word: 'Arid', translation: '乾旱的', definition: 'Having little or no rain.', example: 'Arid region.', level: 'Senior' },
  { id: 's132', word: 'Aspiration', translation: '渴望/抱負', definition: 'A hope of achieving something.', example: 'High aspirations.', level: 'Senior' },
  { id: 's133', word: 'Assiduous', translation: '勤勉的', definition: 'Showing great care and perseverance.', example: 'Assiduous student.', level: 'Senior' },
  { id: 's134', word: 'Assumption', translation: '假設', definition: 'Something accepted as true without proof.', example: 'False assumption.', level: 'Senior' },
  { id: 's135', word: 'Asymmetry', translation: '不對稱', definition: 'Lack of symmetry.', example: 'Visual asymmetry.', level: 'Senior' },
  { id: 's136', word: 'Attain', translation: '獲得', definition: 'To succeed in achieving.', example: 'Attain a goal.', level: 'Senior' },
  { id: 's137', word: 'Attribute', translation: '屬性/歸因於', definition: 'A quality or characteristic.', example: 'Key attribute.', level: 'Senior' },
  { id: 's138', word: 'Augment', translation: '增加', definition: 'To make something greater.', example: 'Augment reality.', level: 'Senior' },
  { id: 's139', word: 'Authentic', translation: '真實的', definition: 'Of undisputed origin; genuine.', example: 'Authentic cuisine.', level: 'Senior' },
  { id: 's140', word: 'Autonomous', translation: '自治的/自主的', definition: 'Acting independently.', example: 'Autonomous vehicle.', level: 'Senior' },
  { id: 's141', word: 'Availability', translation: '可用性', definition: 'State of being usable.', example: 'Product availability.', level: 'Senior' },
  { id: 's142', word: 'Axiom', translation: '公理/公認的真理', definition: 'Self-evident truth.', example: 'Logical axiom.', level: 'Senior' },
  { id: 's143', word: 'Baffle', translation: '困惑', definition: 'Totally bewilder.', example: 'Baffled by the puzzle.', level: 'Senior' },
  { id: 's144', word: 'Barren', translation: '荒蕪的', definition: 'Too poor to produce vegetation.', example: 'Barren land.', level: 'Senior' },
  { id: 's145', word: 'Belittle', translation: '輕視', definition: 'Dismiss as unimportant.', example: 'Don\'t belittle others.', level: 'Senior' },
  { id: 's146', word: 'Beneficiary', translation: '受益者', definition: 'Person who derives advantage.', example: 'Main beneficiary.', level: 'Senior' },
  { id: 's147', word: 'Bias', translation: '偏見', definition: 'Prejudice in favor of one thing.', example: 'Unconscious bias.', level: 'Senior' },
  { id: 's148', word: 'Blatant', translation: '明目張膽的', definition: 'Done openly and unashamedly.', example: 'Blatant lie.', level: 'Senior' },
  { id: 's149', word: 'Breach', translation: '違反/破壞', definition: 'An act of breaking a law.', example: 'Breach of contract.', level: 'Senior' },
  { id: 's150', word: 'Brilliant', translation: '燦爛的/卓越的', definition: 'Exceptionally clever.', example: 'Brilliant mind.', level: 'Senior' },
  { id: 's151', word: 'Bureaucracy', translation: '官僚體制', definition: 'Complex administrative system.', example: 'Government bureaucracy.', level: 'Senior' },
  { id: 's152', word: 'Calculation', translation: '計算', definition: 'Process of using math.', example: 'Accurate calculation.', level: 'Senior' },
  { id: 's153', word: 'Calibrate', translation: '校準', definition: 'Adjust precisely.', example: 'Calibrate the sensor.', level: 'Senior' },
  { id: 's154', word: 'Camouflage', translation: '偽裝', definition: 'Disguising presence.', example: 'Natural camouflage.', level: 'Senior' },
  { id: 's155', word: 'Capability', translation: '能力', definition: 'Power to do something.', example: 'Technical capability.', level: 'Senior' },
  { id: 's156', word: 'Capacity', translation: '容量/能力', definition: 'Maximum amount.', example: 'Full capacity.', level: 'Senior' },
  { id: 's157', word: 'Capitalism', translation: '資本主義', definition: 'Economic system.', example: 'Global capitalism.', level: 'Senior' },
  { id: 's158', word: 'Casualty', translation: '傷亡', definition: 'Person killed or injured.', example: 'War casualty.', level: 'Senior' },
  { id: 's159', word: 'Catalyst', translation: '催化劑', definition: 'Something that speeds up change.', example: 'Political catalyst.', level: 'Senior' },
  { id: 's160', word: 'Catastrophe', translation: '災難', definition: 'Sudden damage or suffering.', example: 'Natural catastrophe.', level: 'Senior' },
  { id: 's161', word: 'Censorship', translation: '審查制度', definition: 'Suppression of speech.', example: 'Media censorship.', level: 'Senior' },
  { id: 's162', word: 'Challenging', translation: '有挑戰性的', definition: 'Testing one\'s abilities.', example: 'Challenging task.', level: 'Senior' },
  { id: 's163', word: 'Chaos', translation: '混亂', definition: 'Complete disorder.', example: 'Total chaos.', level: 'Senior' },
  { id: 's164', word: 'Characteristic', translation: '特徵', definition: 'Typical quality.', example: 'Unique characteristic.', level: 'Senior' },
  { id: 's165', word: 'Charisma', translation: '魅力', definition: 'Compelling attractiveness.', example: 'Personal charisma.', level: 'Senior' },
  { id: 's166', word: 'Chronic', translation: '慢性的', definition: 'Persisting for a long time.', example: 'Chronic illness.', level: 'Senior' },
  { id: 's167', word: 'Chronological', translation: '按時間順序的', definition: 'Following the order of time.', example: 'Chronological order.', level: 'Senior' },
  { id: 's168', word: 'Circulate', translation: '循環/流通', definition: 'Move continuously.', example: 'Circulate information.', level: 'Senior' },
  { id: 's169', word: 'Circumstance', translation: '情況', definition: 'A fact or condition.', example: 'Difficult circumstance.', level: 'Senior' },
  { id: 's170', word: 'Citation', translation: '引用', definition: 'Quotation from a reference.', example: 'Proper citation.', level: 'Senior' },
  { id: 's171', word: 'Civilization', translation: '文明', definition: 'Advanced stage of society.', example: 'Ancient civilization.', level: 'Senior' },
  { id: 's172', word: 'Clarify', translation: '澄清', definition: 'Make less confused.', example: 'Clarify the point.', level: 'Senior' },
  { id: 's173', word: 'Classification', translation: '分類', definition: 'Action of classifying.', example: 'Biological classification.', level: 'Senior' },
  { id: 's174', word: 'Cognitive', translation: '認知的', definition: 'Relating to mental processes.', example: 'Cognitive development.', level: 'Senior' },
  { id: 's175', word: 'Collaboration', translation: '合作', definition: 'Working together.', example: 'Close collaboration.', level: 'Senior' },
  { id: 's176', word: 'Collateral', translation: '擔保物/附屬的', definition: 'Security for a loan.', example: 'Loan collateral.', level: 'Senior' },
  { id: 's177', word: 'Collective', translation: '集體的', definition: 'Done by a group.', example: 'Collective effort.', level: 'Senior' },
  { id: 's178', word: 'Collision', translation: '碰撞', definition: 'An instance of crashing.', example: 'High-speed collision.', level: 'Senior' },
  { id: 's179', word: 'Colloquial', translation: '口語的', definition: 'Used in ordinary conversation.', example: 'Colloquial language.', level: 'Senior' },
  { id: 's180', word: 'Combustion', translation: '燃燒', definition: 'Process of burning.', example: 'Engine combustion.', level: 'Senior' },
  { id: 's181', word: 'Commemoration', translation: '紀念', definition: 'Action of remembering.', example: 'War commemoration.', level: 'Senior' },
  { id: 's182', word: 'Commence', translation: '開始', definition: 'To begin.', example: 'Commence operations.', level: 'Senior' },
  { id: 's183', word: 'Commensurate', translation: '相稱的', definition: 'Corresponding in size/degree.', example: 'Salary commensurate with experience.', level: 'Senior' },
  { id: 's184', word: 'Commodity', translation: '商品', definition: 'Raw material that can be bought.', example: 'Valuable commodity.', level: 'Senior' },
  { id: 's185', word: 'Compact', translation: '緊湊的/契約', definition: 'Closely packed.', example: 'Compact car.', level: 'Senior' },
  { id: 's186', word: 'Compatibility', translation: '相容性', definition: 'State of living together in harmony.', example: 'Software compatibility.', level: 'Senior' },
  { id: 's187', word: 'Compel', translation: '強迫', definition: 'Force to do something.', example: 'Compel obedience.', level: 'Senior' },
  { id: 's188', word: 'Compendium', translation: '摘要/概略', definition: 'Collection of concise information.', example: 'Compendium of facts.', level: 'Senior' },
  { id: 's189', word: 'Compensation', translation: '補償', definition: 'Money awarded for loss.', example: 'Fair compensation.', level: 'Senior' },
  { id: 's190', word: 'Competence', translation: '能力', definition: 'Ability to do something well.', example: 'Professional competence.', level: 'Senior' },
  { id: 's191', word: 'Compilation', translation: '編譯/彙編', definition: 'Action of compiling.', example: 'Data compilation.', level: 'Senior' },
  { id: 's192', word: 'Complement', translation: '補充/配套', definition: 'Thing that completes.', example: 'Perfect complement.', level: 'Senior' },
  { id: 's193', word: 'Complex', translation: '複雜的', definition: 'Not simple.', example: 'Complex system.', level: 'Senior' },
  { id: 's194', word: 'Compliance', translation: '遵守', definition: 'Action of complying with a wish/command.', example: 'Legal compliance.', level: 'Senior' },
  { id: 's195', word: 'Component', translation: '組件', definition: 'Part of a larger whole.', example: 'Key component.', level: 'Senior' },
  { id: 's196', word: 'Composite', translation: '合成的', definition: 'Made up of several parts.', example: 'Composite material.', level: 'Senior' },
  { id: 's197', word: 'Comprehensive', translation: '全面的', definition: 'Including all elements.', example: 'Comprehensive report.', level: 'Senior' },
  { id: 's198', word: 'Compromise', translation: '妥協', definition: 'An agreement reached.', example: 'Make a compromise.', level: 'Senior' },
  { id: 's199', word: 'Compulsory', translation: '義務的/強制性的', definition: 'Required by law or a rule.', example: 'Compulsory education.', level: 'Senior' },
  { id: 's200', word: 'Concave', translation: '凹的', definition: 'Curving inward.', example: 'Concave lens.', level: 'Senior' },
  // ... 這裡將填入至 1000 字
];
